obj-$(CONFIG_ARK7116) +=  ark7116.o
#ark7116-objs := ark7116_zhonghong.o ark7116_core.o
ark7116-objs := ark7116_ark169.o ark7116_core.o
obj-$(CONFIG_RN6752) += rn6752.o

obj-$(CONFIG_ARKN141_ITU656) += arkn141_itu656_drv.o arkn141_itu656_core.o
obj-$(CONFIG_ARK1668_ITU656) += ark1668_itu656.o
obj-$(CONFIG_VIDEO_ARK1668_VIN) += ark1668_vin.o
