#ifndef ARK_SYS_H
#define	ARK_SYS_H

#define ARK_SYS_ADDR  SYS_BASE
/*
 * System register definitions
 */
#define rSYS_BOOT_SAMPLE					*((volatile unsigned int *)(SYS_BASE+0x0))
#define rSYS_CLK_SEL						*((volatile unsigned int *)(SYS_BASE+0x40))
#define rSYS_AHB_CLK_EN						*((volatile unsigned int *)(SYS_BASE+0x44))
#define rSYS_APB_CLK_EN						*((volatile unsigned int *)(SYS_BASE+0x48))
#define rSYS_AXI_CLK_EN						*((volatile unsigned int *)(SYS_BASE+0x4c))
#define rSYS_PER_CLK_EN						*((volatile unsigned int *)(SYS_BASE+0x50))
#define rSYS_LCD_CLK_CFG					*((volatile unsigned int *)(SYS_BASE+0x54))
#define rSYS_SD_CLK_CFG						*((volatile unsigned int *)(SYS_BASE+0x58))
#define rSYS_SD1_CLK_CFG					*((volatile unsigned int *)(SYS_BASE+0x5c))
#define rSYS_DEVICE_CLK_CFG0				*((volatile unsigned int *)(SYS_BASE+0x60))
#define rSYS_DEVICE_CLK_CFG1				*((volatile unsigned int *)(SYS_BASE+0x64))
#define rSYS_DEVICE_CLK_CFG2				*((volatile unsigned int *)(SYS_BASE+0x68)) 
#define rSYS_DEVICE_CLK_CFG3				*((volatile unsigned int *)(SYS_BASE+0x6c)) 
#define rSYS_CLK_DLY_REG					*((volatile unsigned int *)(SYS_BASE+0x70))
#define rSYS_SOFT_RSTNA						*((volatile unsigned int *)(SYS_BASE+0x74))
#define rSYS_SOFT_RSTNB						*((volatile unsigned int *)(SYS_BASE+0x78))
#define rSYS_SD2_CLK_CFG					*((volatile unsigned int *)(SYS_BASE+0x7c))


#define rSYS_PAD_CTR2A					    *((volatile unsigned int *)(SYS_BASE+0xA8))

#define rSYS_ANALOG_REG0					*((volatile unsigned int *)(SYS_BASE+0x140))	
#define rSYS_ANALOG_REG1					*((volatile unsigned int *)(SYS_BASE+0x144))	
#define rSYS_DDR2_PAD_REG					*((volatile unsigned int *)(SYS_BASE+0x148))	 
#define rSYS_PLLRFCK_CTL					*((volatile unsigned int *)(SYS_BASE+0x14c))	
#define rSYS_CPUPLL_CFG						*((volatile unsigned int *)(SYS_BASE+0x150))	
#define rSYS_SYSPLL_CFG						*((volatile unsigned int *)(SYS_BASE+0x154))	
#define rSYS_AUDPLL_CFG						*((volatile unsigned int *)(SYS_BASE+0x158))	
#define rSYS_DDRDLL_RDCLK_CFG					*((volatile unsigned int *)(SYS_BASE+0x15c))	
#define rSYS_DDRDLL_WRCLK_CFG					*((volatile unsigned int *)(SYS_BASE+0x160))	
#define rSYS_DDRDLL_DQS_CFG0					*((volatile unsigned int *)(SYS_BASE+0x164))
#define rSYS_DDRDLL_DQS_CFG1					*((volatile unsigned int *)(SYS_BASE+0x168))
#define rSYS_DDRDLL_DQS_CFG2					*((volatile unsigned int *)(SYS_BASE+0x16C))
#define rSYS_DDRDLL_BIAS_CFG2					*((volatile unsigned int *)(SYS_BASE+0x170))

#define rSYS_BKLT_STATUS					*((volatile unsigned int *)(SYS_BASE+0x174))
#define rSYS_BKLT_CTLA						*((volatile unsigned int *)(SYS_BASE+0x178))

#define rSYS_I2SDAC_ADDRESS					(SYS_BASE+0x174)
#define rSYS_I2SEXT_ADDRESS					(SYS_BASE+0x178)

#define rSYS_BKLT_CTLB						*((volatile unsigned int *)(SYS_BASE+0x17C))
#define rSYS_BKLT_CTLC						*((volatile unsigned int *)(SYS_BASE+0x180))
#define rSYS_BKLT_CTLD						*((volatile unsigned int *)(SYS_BASE+0x184))
#define rSYS_BKLT_CTLE						*((volatile unsigned int *)(SYS_BASE+0x188))
#define rSYS_BKLT_CTLF						*((volatile unsigned int *)(SYS_BASE+0x18C))
#define rSYS_LVDS_CTRL_CFG					*((volatile unsigned int *)(SYS_BASE+0x190))
#define rSYS_LVDS_CTRL_CFG1					*((volatile unsigned int *)(SYS_BASE+0x194))
#define rSYS_DDS_CLK_CFG					*((volatile unsigned int *)(SYS_BASE+0x198))

#define rSYS_PAD_CTRL00						*((volatile unsigned int *)(SYS_BASE+0x1c0))
#define rSYS_PAD_CTRL01						*((volatile unsigned int *)(SYS_BASE+0x1c4))
#define rSYS_PAD_CTRL02						*((volatile unsigned int *)(SYS_BASE+0x1c8))
#define rSYS_PAD_CTRL03						*((volatile unsigned int *)(SYS_BASE+0x1cc))
#define rSYS_PAD_CTRL04						*((volatile unsigned int *)(SYS_BASE+0x1d0))
#define rSYS_PAD_CTRL05						*((volatile unsigned int *)(SYS_BASE+0x1d4))
#define rSYS_PAD_CTRL06						*((volatile unsigned int *)(SYS_BASE+0x1d8))
#define rSYS_PAD_CTRL07						*((volatile unsigned int *)(SYS_BASE+0x1dc))
#define rSYS_PAD_CTRL08						*((volatile unsigned int *)(SYS_BASE+0x1e0))
#define rSYS_PAD_CTRL09						*((volatile unsigned int *)(SYS_BASE+0x1e4))

#define rSYS_PAD_CTRL0A						*((volatile unsigned int *)(SYS_BASE+0x1e8))
#define rSYS_PAD_CTRL0B                     			*((volatile unsigned int *)(SYS_BASE+0x1ec))
#define rSYS_PAD_CTRL0C                     			*((volatile unsigned int *)(SYS_BASE+0x1f0))
#define rSYS_PAD_CTRL0D                     			*((volatile unsigned int *)(SYS_BASE+0x1f4))
#define rSYS_PAD_CTRL0E                     			*((volatile unsigned int *)(SYS_BASE+0x1f8))
#define rSYS_PAD_CTRL38                     			*((volatile unsigned int *)(SYS_BASE+0x1fC))

#define rSYS_PAD_CTRL3E                     			*((volatile unsigned int *)(SYS_BASE+0x200))
#define rSYS_PAD_CTRL0F                    			*((volatile unsigned int *)(SYS_BASE+0x204))
#define rSYS_PAD_CPU_RESET                  			*((volatile unsigned int *)(SYS_BASE+0x208))
#define rSYS_DEVICE_CLK_CFG5					*((volatile unsigned int *)(SYS_BASE+0x228))
#define rSYS_VID_DAC_CFG					*((volatile unsigned int *)(SYS_BASE+0x258))

/* PWM */
#define rPWM_ENA0                                       (*(volatile unsigned int *)(PWM_BASE + 0x00))
#define rPWM_DUTY0                                      (*(volatile unsigned int *)(PWM_BASE + 0x04))
#define rPWM_CNTR0                                      (*(volatile unsigned int *)(PWM_BASE + 0x08))
#define rPWM_ENA1                                       (*(volatile unsigned int *)(PWM_BASE + 0x10))
#define rPWM_DUTY1                                      (*(volatile unsigned int *)(PWM_BASE + 0x14))
#define rPWM_CNTR1                                      (*(volatile unsigned int *)(PWM_BASE + 0x18))
#define rPWM_ENA2                                       (*(volatile unsigned int *)(PWM_BASE + 0x20))
#define rPWM_DUTY2                                      (*(volatile unsigned int *)(PWM_BASE + 0x24))
#define rPWM_CNTR2                                      (*(volatile unsigned int *)(PWM_BASE + 0x28))
#define rPWM_ENA3                                       (*(volatile unsigned int *)(PWM_BASE + 0x30))
#define rPWM_DUTY3                                      (*(volatile unsigned int *)(PWM_BASE + 0x34))
#define rPWM_CNTR3                                      (*(volatile unsigned int *)(PWM_BASE + 0x38))
#define rPWM_ENA4                                       (*(volatile unsigned int *)(PWM_BASE + 0x40))
#define rPWM_DUTY4                                      (*(volatile unsigned int *)(PWM_BASE + 0x44))
#define rPWM_CNTR4                                      (*(volatile unsigned int *)(PWM_BASE + 0x48))
#define rPWM_ENA5                                       (*(volatile unsigned int *)(PWM_BASE + 0x50))
#define rPWM_DUTY5                                      (*(volatile unsigned int *)(PWM_BASE + 0x54))
#define rPWM_CNTR5                                      (*(volatile unsigned int *)(PWM_BASE + 0x58))

/* LCD */
#define rLCD_EANBLE								*((volatile unsigned int *)(LCD_BASE+0x000))
#define rLCD_CONTROL								*((volatile unsigned int *)(LCD_BASE+0x004))
#define rLCD_TIMING0								*((volatile unsigned int *)(LCD_BASE+0x008))
#define rLCD_TIMING1								*((volatile unsigned int *)(LCD_BASE+0x00c))
#define rLCD_TIMING2								*((volatile unsigned int *)(LCD_BASE+0x010))
#define rLCD_TIMING3								*((volatile unsigned int *)(LCD_BASE+0x014))
#define rLCD_TIMING_FRAME_START_CNT_LCD				    		*((volatile unsigned int *)(LCD_BASE+0x018))
#define rLCD_BACK_COLOR								*((volatile unsigned int *)(LCD_BASE+0x01C))
#define rLCD_BLD_MODE_LCD_REG0						    	*((volatile unsigned int *)(LCD_BASE+0x020))
#define rLCD_BLD_MODE_LCD_REG1							*((volatile unsigned int *)(LCD_BASE+0x024))
#define rLCD_BLEND_POST_CTL  							*((volatile unsigned int *)(LCD_BASE+0x028))                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
#define rLCD_ITU_CONTROL                                			*((volatile unsigned int *)(LCD_BASE+0x02C)) 
#define rCLCD_ITU_SRGB_GENERATION_CTL						*((volatile unsigned int *)(LCD_BASE+0x030))
#define rLCD_ITU_TIMIING_REFERENCE_CODE_DEFINE					*((volatile unsigned int *)(LCD_BASE+0x034))//new                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_YCLCD_ITU_TIMING_REFERENCE_CODE_DEFINE				*((volatile unsigned int *)(LCD_BASE+0x038))//new                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_DITHERING								*((volatile unsigned int *)(LCD_BASE+0x03C))//new
#define rLCD_DITHERING_V_H_SIZE							*((volatile unsigned int *)(LCD_BASE+0x040))//new
#define rLCD_DITHERING_TEST							*((volatile unsigned int *)(LCD_BASE+0x044))//new

#define rLCD_ITU1120_REG0							*((volatile unsigned int *)(LCD_BASE+0x050))//new
#define rLCD_ITU1120_REG1							*((volatile unsigned int *)(LCD_BASE+0x054))//new
#define rLCD_TV_CONTROL								*((volatile unsigned int *)(LCD_BASE+0x060))
#define rLCD_TIMING0_TV								*((volatile unsigned int *)(LCD_BASE             +0x064))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_TIMING1_TV								*((volatile unsigned int *)(LCD_BASE+0x068))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_TIMING2_TV								*((volatile unsigned int *)(LCD_BASE+0x06c))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_TIMING3_TV								*((volatile unsigned int *)(LCD_BASE+0x070))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_TIMING_FRAME_START_CNT_TV						*((volatile unsigned int *)(LCD_BASE+0x074))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_BACK_COLOR_TV							*((volatile unsigned int *)(LCD_BASE+0x078))                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
#define rLCD_BLD_MODE_TV_REG0							*((volatile unsigned int *)(LCD_BASE+0x07C))
#define rLCD_BLD_MODE_TV_REG1							*((volatile unsigned int *)(LCD_BASE+0x080))

//TV Encoder param
#define rLCD_TV_PARAM_REG0  							*((volatile unsigned int *)(LCD_BASE+0x084))
#define rLCD_TV_PARAM_REG1  							*((volatile unsigned int *)(LCD_BASE+0x088))
#define rLCD_TV_PARAM_REG2  							*((volatile unsigned int *)(LCD_BASE+0x08c))
#define rLCD_TV_PARAM_REG3  							*((volatile unsigned int *)(LCD_BASE+0x090))
#define rLCD_TV_PARAM_REG4  							*((volatile unsigned int *)(LCD_BASE+0x094))
#define rLCD_TV_PARAM_REG5  							*((volatile unsigned int *)(LCD_BASE+0x098))
#define rLCD_TV_PARAM_REG6  							*((volatile unsigned int *)(LCD_BASE+0x09C))
#define rLCD_TV_PARAM_REG7  							*((volatile unsigned int *)(LCD_BASE+0x0A0))
#define rLCD_TV_PARAM_REG8  							*((volatile unsigned int *)(LCD_BASE+0x0A4))
#define rLCD_TV_PARAM_REG9  							*((volatile unsigned int *)(LCD_BASE+0x0A8))
#define rLCD_TV_PARAM_REG10 							*((volatile unsigned int *)(LCD_BASE+0x0AC))
#define rLCD_TV_PARAM_REG11 							*((volatile unsigned int *)(LCD_BASE+0x0B0))
#define rLCD_TV_PARAM_REG12 							*((volatile unsigned int *)(LCD_BASE+0x0B4))
#define rLCD_TV_PARAM_REG13 							*((volatile unsigned int *)(LCD_BASE+0x0B8))
#define rLCD_TV_PARAM_REG14 							*((volatile unsigned int *)(LCD_BASE+0x0BC))
#define rLCD_TV_PARAM_REG15 							*((volatile unsigned int *)(LCD_BASE+0x0C0))
#define rLCD_TV_PARAM_REG16 							*((volatile unsigned int *)(LCD_BASE+0x0C4))
#define rLCD_TV_PARAM_REG17 							*((volatile unsigned int *)(LCD_BASE+0x0C8))
#define rLCD_TV_PARAM_REG18 							*((volatile unsigned int *)(LCD_BASE+0x0CC))
#define rLCD_TV_PARAM_REG19 							*((volatile unsigned int *)(LCD_BASE+0x0D0))
#define rLCD_TV_PARAM_REG20 							*((volatile unsigned int *)(LCD_BASE+0x0D4))
#define rLCD_TV_PARAM_REG21 							*((volatile unsigned int *)(LCD_BASE+0x0D8))


#define rLCD_VIDEO1_BURST_CTL							*((volatile unsigned int *)(LCD_BASE+0x100))
#define rLCD_VIDEO1_CTL								*((volatile unsigned int *)(LCD_BASE+0x104))
#define rLCD_VIDEO1_ALPHA1_ALPHA0_BLENDING_COEFF				*((volatile unsigned int *)(LCD_BASE+0x108))
#define rLCD_VIDEO1_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x10c)) 
#define rLCD_VIDEO1_WIN_SIZE							*((volatile unsigned int *)(LCD_BASE+0x110))
#define rLCD_VIDEO1_SIZE							*((volatile unsigned int *)(LCD_BASE+0x114))
#define rLCD_VIDEO1_WIN_POINT							*((volatile unsigned int *)(LCD_BASE+0x118))
#define rLCD_VIDEO1_POSITION							*((volatile unsigned int *)(LCD_BASE+0x11c))
#define rLCD_VIDEO1_ADDR1							*((volatile unsigned int *)(LCD_BASE+0x120))
#define rLCD_VIDEO1_ADDR2							*((volatile unsigned int *)(LCD_BASE+0x124))
#define rLCD_VIDEO1_ADDR3							*((volatile unsigned int *)(LCD_BASE+0x128))
#define rLCD_VIDEO1_ADDR1_GROUP1						*((volatile unsigned int *)(LCD_BASE+0x12c))
#define rLCD_VIDEO1_ADDR2_GROUP1						*((volatile unsigned int *)(LCD_BASE+0x130))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_VIDEO1_ADDR3_GROUP1						*((volatile unsigned int *)(LCD_BASE+0x134))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_BLD_CUT_LEFT_RIGHT_VIDEO1						*((volatile unsigned int *)(LCD_BASE+0x138))
#define rLCD_BLD_CUT_UP_DOWN_VIDEO1						*((volatile unsigned int *)(LCD_BASE+0x13C))

#define rLCD_COLOR_KEY_MASK_VALUE_VIDEO1					*((volatile unsigned int *)(LCD_BASE+0x140))
#define rLCD_COLOR_KEY_MASK_THLD_VIDEO1						*((volatile unsigned int *)(LCD_BASE+0x144))
#define rLCD_VIDEO1_RIGHT_BOTTOM_CUT_NUM					*((volatile unsigned int *)(LCD_BASE+0x148))
#define rLCD_VIDEO1_SCALE_VXMOD						    	*((volatile unsigned int *)(LCD_BASE+0x14C))
#define rLCD_VIDEO1_SCALE_CTL							*((volatile unsigned int *)(LCD_BASE+0x150))
#define rLCD_VIDEO1_SCAL_CTL0							*((volatile unsigned int *)(LCD_BASE+0x154))
#define rLCD_VIDEO1_SCAL_CTL1							*((volatile unsigned int *)(LCD_BASE+0x158))
#define rLCD_VIDEO1_SCAL_CTL2							*((volatile unsigned int *)(LCD_BASE+0x15C))
#define rLCD_VIDEO1_SCAL_CTL3							*((volatile unsigned int *)(LCD_BASE+0x160))
#define rLCD_VIDEO1_SCAL_CTL4							*((volatile unsigned int *)(LCD_BASE+0x164))
#define rLCD_VIDEO1_HSCAL_COS_VALUE						*((volatile unsigned int *)(LCD_BASE+0x168))

#define rLCD_VIDEO1_SCALER_OFFSET						*((volatile unsigned int *)(LCD_BASE+0x16C))


#define rLCD_VIDEO2_BURST_CTL							*((volatile unsigned int *)(LCD_BASE+0x180))
#define rLCD_VIDEO2_CTL								*((volatile unsigned int *)(LCD_BASE+0x184))
#define rLCD_VIDEO2_ALPHA1_ALPHA0_BLENDING_COEFF				*((volatile unsigned int *)(LCD_BASE+0x188))//NEW
#define rLCD_VIDEO2_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x18c))
#define rLCD_VIDEO2_WIN_POINT							*((volatile unsigned int *)(LCD_BASE+0x190))
#define rLCD_VIDEO2_WIN_SIZE							*((volatile unsigned int *)(LCD_BASE+0x194))
#define rLCD_VIDEO2_SIZE							*((volatile unsigned int *)(LCD_BASE+0x198))
#define rLCD_VIDEO2_POSITION							*((volatile unsigned int *)(LCD_BASE+0x19c))
#define rLCD_VIDEO2_ADDR1							*((volatile unsigned int *)(LCD_BASE+0x1A0))
#define rLCD_VIDEO2_ADDR2							*((volatile unsigned int *)(LCD_BASE+0x1A4))
#define rLCD_VIDEO2_ADDR3							*((volatile unsigned int *)(LCD_BASE+0x1A8))
#define rLCD_VIDEO2_ADDR1_GROUP1						*((volatile unsigned int *)(LCD_BASE+0x1AC))
#define rLCD_VIDEO2_ADDR2_GROUP1						*((volatile unsigned int *)(LCD_BASE+0x1B0))
#define rLCD_VIDEO2_ADDR3_GROUP1						*((volatile unsigned int *)(LCD_BASE+0x1B4))	
#define rLCD_BLD_CUT_LEFT_RIGHT_VIDEO2						*((volatile unsigned int *)(LCD_BASE+0x1B8))
#define rLCD_BLD_CUT_UP_DOWN_VIDEO2						*((volatile unsigned int *)(LCD_BASE+0x1BC))
#define rLCD_COLOR_KEY_MASK_VALUE_VIDEO2					*((volatile unsigned int *)(LCD_BASE+0x1C0))
#define rLCD_COLOR_KEY_MASK_THLD_VIDEO2						*((volatile unsigned int *)(LCD_BASE+0x1C4))

#define rLCD_OSD1_BURST_CTL							*((volatile unsigned int *)(LCD_BASE+0x1E0))
#define rLCD_OSD1_CTL								*((volatile unsigned int *)(LCD_BASE+0x1E4))
#define rLCD_ALPHA1_0_OSD1							*((volatile unsigned int *)(LCD_BASE+0x1E8))
#define rLCD_OSD1_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x1EC)) 
#define rLCD_OSD1_SIZE								*((volatile unsigned int *)(LCD_BASE+0x1F0))
#define rLCD_OSD1_WIN_POINT							*((volatile unsigned int *)(LCD_BASE+0x1F4))
#define rLCD_OSD1_POSITION							*((volatile unsigned int *)(LCD_BASE+0x1F8))
#define rLCD_OSD1_ADDR								*((volatile unsigned int *)(LCD_BASE+0x1FC))
#define rLCD_OSD1_ADDR_GROUP1							*((volatile unsigned int *)(LCD_BASE+0x200))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_BLD_CUT_LEFT_RIGHT_OSD1						*((volatile unsigned int *)(LCD_BASE+0x204))
#define rLCD_BLD_CUT_UP_DOWN_OSD1						*((volatile unsigned int *)(LCD_BASE+0x208))
#define rLCD_COLOR_KEY_MASK_VALUE_OSD1						*((volatile unsigned int *)(LCD_BASE+0x20c))
#define rLCD_COLOR_KEY_MASK_THLD_OSD1						*((volatile unsigned int *)(LCD_BASE+0x210))


#define rLCD_OSD2_BURST_CTL							*((volatile unsigned int *)(LCD_BASE+0x230))
#define rLCD_OSD2_CTL								*((volatile unsigned int *)(LCD_BASE+0x234))
#define rLCD_ALPHA1_0_OSD2							*((volatile unsigned int *)(LCD_BASE+0x238))
#define rLCD_OSD2_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x23C)) 
#define rLCD_OSD2_SIZE								*((volatile unsigned int *)(LCD_BASE+0x240))
#define rLCD_OSD2_WIN_POINT							*((volatile unsigned int *)(LCD_BASE+0x244))
#define rLCD_OSD2_POSITION							*((volatile unsigned int *)(LCD_BASE+0x248))
#define rLCD_OSD2_ADDR								*((volatile unsigned int *)(LCD_BASE+0x24C))
#define rLCD_OSD2_ADDR_GROUP1							*((volatile unsigned int *)(LCD_BASE+0x250))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_BLD_CUT_LEFT_RIGHT_OSD2						*((volatile unsigned int *)(LCD_BASE+0x254))
#define rLCD_BLD_CUT_UP_DOWN_OSD2						*((volatile unsigned int *)(LCD_BASE+0x258))
#define rLCD_COLOR_KEY_MASK_VALUE_OSD2						*((volatile unsigned int *)(LCD_BASE+0x25c))
#define rLCD_COLOR_KEY_MASK_THLD_OSD2						*((volatile unsigned int *)(LCD_BASE+0x260))


#define rLCD_OSD3_BURST_CTL							*((volatile unsigned int *)(LCD_BASE+0x280))
#define rLCD_OSD3_CTL								*((volatile unsigned int *)(LCD_BASE+0x284))
#define rLCD_ALPHA1_0_OSD3							*((volatile unsigned int *)(LCD_BASE+0x288))
#define rLCD_OSD3_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x28C)) 
#define rLCD_OSD3_SIZE								*((volatile unsigned int *)(LCD_BASE+0x290))
#define rLCD_OSD3_WIN_POINT							*((volatile unsigned int *)(LCD_BASE+0x294))
#define rLCD_OSD3_POSITION							*((volatile unsigned int *)(LCD_BASE+0x298))
#define rLCD_OSD3_ADDR								*((volatile unsigned int *)(LCD_BASE+0x29C))
#define rLCD_OSD3_ADDR_GROUP1							*((volatile unsigned int *)(LCD_BASE+0x2A0))                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
#define rLCD_BLD_CUT_LEFT_RIGHT_OSD3						*((volatile unsigned int *)(LCD_BASE+0x2A4))
#define rLCD_BLD_CUT_UP_DOWN_OSD3						*((volatile unsigned int *)(LCD_BASE+0x2A8))
#define rLCD_COLOR_KEY_MASK_VALUE_OSD3						*((volatile unsigned int *)(LCD_BASE+0x2Ac))
#define rLCD_COLOR_KEY_MASK_THLD_OSD3						*((volatile unsigned int *)(LCD_BASE+0x2B0))

#define rLCD_TIMING_INIT							*((volatile unsigned int *)(LCD_BASE+0x2CC))
#define rLCD_INTERRUPT_CTL							*((volatile unsigned int *)(LCD_BASE+0x2D0))
#define rLCD_INTERRUPT_STATUS							*((volatile unsigned int *)(LCD_BASE+0x2D4))
#define rLCD_PARAMTERS_SYNC_SWITCH						*((volatile unsigned int *)(LCD_BASE+0x2D8))//new

#define rLCD_GAMMA_REG_0							*((volatile unsigned int *)(LCD_BASE+0x2Dc))
#define rLCD_GAMMA_REG_1							*((volatile unsigned int *)(LCD_BASE+0x2E0))
#define rLCD_GAMMA_REG_2							*((volatile unsigned int *)(LCD_BASE+0x2E4))
#define rLCD_GAMMA_REG_3							*((volatile unsigned int *)(LCD_BASE+0x2E8))
#define rLCD_GAMMA_REG_4							*((volatile unsigned int *)(LCD_BASE+0x2Ec))
#define rLCD_GAMMA_REG_5							*((volatile unsigned int *)(LCD_BASE+0x2F0))
#define rLCD_GAMMA_REG_6							*((volatile unsigned int *)(LCD_BASE+0x2F4))
#define rLCD_GAMMA_REG_7							*((volatile unsigned int *)(LCD_BASE+0x2F8))
#define rLCD_GAMMA_REG_8							*((volatile unsigned int *)(LCD_BASE+0x2Fc))
#define rLCD_GAMMA_REG_9							*((volatile unsigned int *)(LCD_BASE+0x300))
#define rLCD_GAMMA_REG_10							*((volatile unsigned int *)(LCD_BASE+0x304))
#define rLCD_GAMMA_REG_11							*((volatile unsigned int *)(LCD_BASE+0x308))
#define rLCD_GAMMA_REG_12							*((volatile unsigned int *)(LCD_BASE+0x30c))
#define rLCD_GAMMA_REG_13							*((volatile unsigned int *)(LCD_BASE+0x310))
#define rLCD_GAMMA_REG_14							*((volatile unsigned int *)(LCD_BASE+0x314))
#define rLCD_GAMMA_REG_15							*((volatile unsigned int *)(LCD_BASE+0x318))
#define rLCD_GAMMA_REG_16							*((volatile unsigned int *)(LCD_BASE+0x31c))
#define rLCD_GAMMA_REG_17							*((volatile unsigned int *)(LCD_BASE+0x320))
#define rLCD_GAMMA_REG_18							*((volatile unsigned int *)(LCD_BASE+0x324))
#define rLCD_GAMMA_REG_19							*((volatile unsigned int *)(LCD_BASE+0x328))
#define rLCD_GAMMA_REG_20							*((volatile unsigned int *)(LCD_BASE+0x32c))
#define rLCD_GAMMA_REG_21							*((volatile unsigned int *)(LCD_BASE+0x330))
#define rLCD_GAMMA_REG_22							*((volatile unsigned int *)(LCD_BASE+0x334))
#define rLCD_GAMMA_REG_23							*((volatile unsigned int *)(LCD_BASE+0x338))
#define rLCD_GAMMA_REG_24							*((volatile unsigned int *)(LCD_BASE+0x33c))
#define rLCD_GAMMA_REG_25							*((volatile unsigned int *)(LCD_BASE+0x340))
#define rLCD_GAMMA_REG_26							*((volatile unsigned int *)(LCD_BASE+0x344))
#define rLCD_GAMMA_REG_27							*((volatile unsigned int *)(LCD_BASE+0x348))
#define rLCD_GAMMA_REG_28							*((volatile unsigned int *)(LCD_BASE+0x34c))
#define rLCD_GAMMA_REG_29							*((volatile unsigned int *)(LCD_BASE+0x350))
#define rLCD_GAMMA_REG_30							*((volatile unsigned int *)(LCD_BASE+0x354))
#define rLCD_GAMMA_REG_31							*((volatile unsigned int *)(LCD_BASE+0x358))
#define rLCD_GAMMA_REG_32							*((volatile unsigned int *)(LCD_BASE+0x35c))
#define rLCD_GAMMA_REG_33							*((volatile unsigned int *)(LCD_BASE+0x360))
#define rLCD_GAMMA_REG_34							*((volatile unsigned int *)(LCD_BASE+0x364))
#define rLCD_GAMMA_REG_35							*((volatile unsigned int *)(LCD_BASE+0x368))
#define rLCD_GAMMA_REG_36							*((volatile unsigned int *)(LCD_BASE+0x36c))
#define rLCD_GAMMA_REG_37							*((volatile unsigned int *)(LCD_BASE+0x370))
#define rLCD_GAMMA_REG_38							*((volatile unsigned int *)(LCD_BASE+0x374))
#define rLCD_GAMMA_REG_39							*((volatile unsigned int *)(LCD_BASE+0x378))
#define rLCD_GAMMA_REG_40							*((volatile unsigned int *)(LCD_BASE+0x37c))
#define rLCD_GAMMA_REG_41							*((volatile unsigned int *)(LCD_BASE+0x380))
#define rLCD_GAMMA_REG_42							*((volatile unsigned int *)(LCD_BASE+0x384))
#define rLCD_GAMMA_REG_43							*((volatile unsigned int *)(LCD_BASE+0x388))
#define rLCD_GAMMA_REG_44							*((volatile unsigned int *)(LCD_BASE+0x38c))
#define rLCD_GAMMA_REG_45							*((volatile unsigned int *)(LCD_BASE+0x390))
#define rLCD_GAMMA_REG_46							*((volatile unsigned int *)(LCD_BASE+0x394))
#define rLCD_GAMMA_REG_47							*((volatile unsigned int *)(LCD_BASE+0x398))
#define rLCD_GAMMA_REG_48							*((volatile unsigned int *)(LCD_BASE+0x39c))



#define rLCD_TV_GAMMA_REG_0							*((volatile unsigned int *)(LCD_BASE+0x3A0))
#define rLCD_TV_GAMMA_REG_1							*((volatile unsigned int *)(LCD_BASE+0x3A4))
#define rLCD_TV_GAMMA_REG_2							*((volatile unsigned int *)(LCD_BASE+0x3A8))
#define rLCD_TV_GAMMA_REG_3							*((volatile unsigned int *)(LCD_BASE+0x3AC))
#define rLCD_TV_GAMMA_REG_4							*((volatile unsigned int *)(LCD_BASE+0x3B0))
#define rLCD_TV_GAMMA_REG_5							*((volatile unsigned int *)(LCD_BASE+0x3B4))
#define rLCD_TV_GAMMA_REG_6							*((volatile unsigned int *)(LCD_BASE+0x3B8))
#define rLCD_TV_GAMMA_REG_7							*((volatile unsigned int *)(LCD_BASE+0x3BC))
#define rLCD_TV_GAMMA_REG_8							*((volatile unsigned int *)(LCD_BASE+0x3C0))
#define rLCD_TV_GAMMA_REG_9							*((volatile unsigned int *)(LCD_BASE+0x3C4))
#define rLCD_TV_GAMMA_REG_10							*((volatile unsigned int *)(LCD_BASE+0x3C8))
#define rLCD_TV_GAMMA_REG_11							*((volatile unsigned int *)(LCD_BASE+0x3CC))
#define rLCD_TV_GAMMA_REG_12							*((volatile unsigned int *)(LCD_BASE+0x3D0))
#define rLCD_TV_GAMMA_REG_13							*((volatile unsigned int *)(LCD_BASE+0x3D4))
#define rLCD_TV_GAMMA_REG_14							*((volatile unsigned int *)(LCD_BASE+0x3D8))
#define rLCD_TV_GAMMA_REG_15							*((volatile unsigned int *)(LCD_BASE+0x3DC))
#define rLCD_TV_GAMMA_REG_16							*((volatile unsigned int *)(LCD_BASE+0x3E0))
#define rLCD_TV_GAMMA_REG_17							*((volatile unsigned int *)(LCD_BASE+0x3E4))
#define rLCD_TV_GAMMA_REG_18							*((volatile unsigned int *)(LCD_BASE+0x3E8))
#define rLCD_TV_GAMMA_REG_19							*((volatile unsigned int *)(LCD_BASE+0x3EC))
#define rLCD_TV_GAMMA_REG_20							*((volatile unsigned int *)(LCD_BASE+0x3F0))
#define rLCD_TV_GAMMA_REG_21							*((volatile unsigned int *)(LCD_BASE+0x3F4))
#define rLCD_TV_GAMMA_REG_22							*((volatile unsigned int *)(LCD_BASE+0x3F8))
#define rLCD_TV_GAMMA_REG_23							*((volatile unsigned int *)(LCD_BASE+0x3FC))
#define rLCD_TV_GAMMA_REG_24							*((volatile unsigned int *)(LCD_BASE+0x400))
#define rLCD_TV_GAMMA_REG_25							*((volatile unsigned int *)(LCD_BASE+0x404))
#define rLCD_TV_GAMMA_REG_26							*((volatile unsigned int *)(LCD_BASE+0x408))
#define rLCD_TV_GAMMA_REG_27							*((volatile unsigned int *)(LCD_BASE+0x40C))
#define rLCD_TV_GAMMA_REG_28							*((volatile unsigned int *)(LCD_BASE+0x410))
#define rLCD_TV_GAMMA_REG_29							*((volatile unsigned int *)(LCD_BASE+0x414))
#define rLCD_TV_GAMMA_REG_30							*((volatile unsigned int *)(LCD_BASE+0x418))
#define rLCD_TV_GAMMA_REG_31							*((volatile unsigned int *)(LCD_BASE+0x41C))
#define rLCD_TV_GAMMA_REG_32							*((volatile unsigned int *)(LCD_BASE+0x420))
#define rLCD_TV_GAMMA_REG_33							*((volatile unsigned int *)(LCD_BASE+0x424))
#define rLCD_TV_GAMMA_REG_34							*((volatile unsigned int *)(LCD_BASE+0x428))
#define rLCD_TV_GAMMA_REG_35							*((volatile unsigned int *)(LCD_BASE+0x42C))
#define rLCD_TV_GAMMA_REG_36							*((volatile unsigned int *)(LCD_BASE+0x430))
#define rLCD_TV_GAMMA_REG_37							*((volatile unsigned int *)(LCD_BASE+0x434))
#define rLCD_TV_GAMMA_REG_38							*((volatile unsigned int *)(LCD_BASE+0x438))
#define rLCD_TV_GAMMA_REG_39							*((volatile unsigned int *)(LCD_BASE+0x43C))
#define rLCD_TV_GAMMA_REG_40							*((volatile unsigned int *)(LCD_BASE+0x440))
#define rLCD_TV_GAMMA_REG_41							*((volatile unsigned int *)(LCD_BASE+0x444))
#define rLCD_TV_GAMMA_REG_42							*((volatile unsigned int *)(LCD_BASE+0x448))
#define rLCD_TV_GAMMA_REG_43							*((volatile unsigned int *)(LCD_BASE+0x44C))
#define rLCD_TV_GAMMA_REG_44							*((volatile unsigned int *)(LCD_BASE+0x450))
#define rLCD_TV_GAMMA_REG_45							*((volatile unsigned int *)(LCD_BASE+0x454))
#define rLCD_TV_GAMMA_REG_46							*((volatile unsigned int *)(LCD_BASE+0x458))
#define rLCD_TV_GAMMA_REG_47							*((volatile unsigned int *)(LCD_BASE+0x45C))
#define rLCD_TV_GAMMA_REG_48							*((volatile unsigned int *)(LCD_BASE+0x460))


#define rLCD_VIDEO1_LAYER_GAMMA_REG_0					*((volatile unsigned int *)(LCD_BASE+0x464))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_1					*((volatile unsigned int *)(LCD_BASE+0x468))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_2					*((volatile unsigned int *)(LCD_BASE+0x46C))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_3					*((volatile unsigned int *)(LCD_BASE+0x470))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_4					*((volatile unsigned int *)(LCD_BASE+0x474))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_5					*((volatile unsigned int *)(LCD_BASE+0x478))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_6					*((volatile unsigned int *)(LCD_BASE+0x47C))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_7					*((volatile unsigned int *)(LCD_BASE+0x480))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_8					*((volatile unsigned int *)(LCD_BASE+0x484))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_9					*((volatile unsigned int *)(LCD_BASE+0x488))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_10					*((volatile unsigned int *)(LCD_BASE+0x48C))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_11					*((volatile unsigned int *)(LCD_BASE+0x490))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_12					*((volatile unsigned int *)(LCD_BASE+0x494))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_13					*((volatile unsigned int *)(LCD_BASE+0x498))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_14					*((volatile unsigned int *)(LCD_BASE+0x49C))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_15					*((volatile unsigned int *)(LCD_BASE+0x4A0))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_16					*((volatile unsigned int *)(LCD_BASE+0x4A4))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_17					*((volatile unsigned int *)(LCD_BASE+0x4A8))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_18					*((volatile unsigned int *)(LCD_BASE+0x4AC))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_19					*((volatile unsigned int *)(LCD_BASE+0x4B0))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_20					*((volatile unsigned int *)(LCD_BASE+0x4B4))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_21					*((volatile unsigned int *)(LCD_BASE+0x4B8))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_22					*((volatile unsigned int *)(LCD_BASE+0x4BC))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_23					*((volatile unsigned int *)(LCD_BASE+0x4C0))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_24					*((volatile unsigned int *)(LCD_BASE+0x4C4))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_25					*((volatile unsigned int *)(LCD_BASE+0x4C8))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_26					*((volatile unsigned int *)(LCD_BASE+0x4CC))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_27					*((volatile unsigned int *)(LCD_BASE+0x4D0))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_28					*((volatile unsigned int *)(LCD_BASE+0x4D4))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_29					*((volatile unsigned int *)(LCD_BASE+0x4D8))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_30					*((volatile unsigned int *)(LCD_BASE+0x4DC))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_31					*((volatile unsigned int *)(LCD_BASE+0x4E0))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_32					*((volatile unsigned int *)(LCD_BASE+0x4E4))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_33					*((volatile unsigned int *)(LCD_BASE+0x4E8))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_34					*((volatile unsigned int *)(LCD_BASE+0x4EC))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_35					*((volatile unsigned int *)(LCD_BASE+0x4F0))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_36					*((volatile unsigned int *)(LCD_BASE+0x4F4))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_37					*((volatile unsigned int *)(LCD_BASE+0x4F8))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_38					*((volatile unsigned int *)(LCD_BASE+0x4FC))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_39					*((volatile unsigned int *)(LCD_BASE+0x500))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_40					*((volatile unsigned int *)(LCD_BASE+0x504))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_41					*((volatile unsigned int *)(LCD_BASE+0x508))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_42					*((volatile unsigned int *)(LCD_BASE+0x50C))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_43					*((volatile unsigned int *)(LCD_BASE+0x510))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_44					*((volatile unsigned int *)(LCD_BASE+0x514))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_45					*((volatile unsigned int *)(LCD_BASE+0x518))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_46					*((volatile unsigned int *)(LCD_BASE+0x51C))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_47					*((volatile unsigned int *)(LCD_BASE+0x520))
#define rLCD_VIDEO1_LAYER_GAMMA_REG_48					*((volatile unsigned int *)(LCD_BASE+0x524))


#define rLCD_VIDEO2_LAYER_GAMMA_REG_0					*((volatile unsigned int *)(LCD_BASE+0x528))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_1					*((volatile unsigned int *)(LCD_BASE+0x52C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_2					*((volatile unsigned int *)(LCD_BASE+0x530))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_3					*((volatile unsigned int *)(LCD_BASE+0x534))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_4					*((volatile unsigned int *)(LCD_BASE+0x538))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_5					*((volatile unsigned int *)(LCD_BASE+0x53C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_6					*((volatile unsigned int *)(LCD_BASE+0x540))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_7					*((volatile unsigned int *)(LCD_BASE+0x544))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_8					*((volatile unsigned int *)(LCD_BASE+0x548))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_9					*((volatile unsigned int *)(LCD_BASE+0x54C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_10					*((volatile unsigned int *)(LCD_BASE+0x550))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_11					*((volatile unsigned int *)(LCD_BASE+0x554))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_12					*((volatile unsigned int *)(LCD_BASE+0x558))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_13					*((volatile unsigned int *)(LCD_BASE+0x55C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_14					*((volatile unsigned int *)(LCD_BASE+0x560))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_15					*((volatile unsigned int *)(LCD_BASE+0x564))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_16					*((volatile unsigned int *)(LCD_BASE+0x568))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_17					*((volatile unsigned int *)(LCD_BASE+0x56C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_18					*((volatile unsigned int *)(LCD_BASE+0x570))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_19					*((volatile unsigned int *)(LCD_BASE+0x574))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_20					*((volatile unsigned int *)(LCD_BASE+0x578))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_21					*((volatile unsigned int *)(LCD_BASE+0x57C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_22					*((volatile unsigned int *)(LCD_BASE+0x580))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_23					*((volatile unsigned int *)(LCD_BASE+0x584))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_24					*((volatile unsigned int *)(LCD_BASE+0x588))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_25					*((volatile unsigned int *)(LCD_BASE+0x58C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_26					*((volatile unsigned int *)(LCD_BASE+0x590))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_27					*((volatile unsigned int *)(LCD_BASE+0x594))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_28					*((volatile unsigned int *)(LCD_BASE+0x598))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_29					*((volatile unsigned int *)(LCD_BASE+0x59C))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_30					*((volatile unsigned int *)(LCD_BASE+0x5A0))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_31					*((volatile unsigned int *)(LCD_BASE+0x5A4))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_32					*((volatile unsigned int *)(LCD_BASE+0x5A8))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_33					*((volatile unsigned int *)(LCD_BASE+0x5AC))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_34					*((volatile unsigned int *)(LCD_BASE+0x5B0))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_35					*((volatile unsigned int *)(LCD_BASE+0x5B4))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_36					*((volatile unsigned int *)(LCD_BASE+0x5B8))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_37					*((volatile unsigned int *)(LCD_BASE+0x5BC))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_38					*((volatile unsigned int *)(LCD_BASE+0x5C0))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_39					*((volatile unsigned int *)(LCD_BASE+0x5C4))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_40					*((volatile unsigned int *)(LCD_BASE+0x5C8))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_41					*((volatile unsigned int *)(LCD_BASE+0x5CC))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_42					*((volatile unsigned int *)(LCD_BASE+0x5D0))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_43					*((volatile unsigned int *)(LCD_BASE+0x5D4))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_44					*((volatile unsigned int *)(LCD_BASE+0x5DC))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_45					*((volatile unsigned int *)(LCD_BASE+0x5E8))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_46					*((volatile unsigned int *)(LCD_BASE+0x5E0))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_47					*((volatile unsigned int *)(LCD_BASE+0x5E4))
#define rLCD_VIDEO2_LAYER_GAMMA_REG_48					*((volatile unsigned int *)(LCD_BASE+0x5E8))

#define rLCD_LCD_COLOUR_MATRIX_REG0                     *((volatile unsigned int *)(LCD_BASE+0x5EC))
#define rLCD_LCD_COLOUR_MATRIX_REG1                     *((volatile unsigned int *)(LCD_BASE+0x5F0))
#define rLCD_LCD_COLOUR_MATRIX_REG2                     *((volatile unsigned int *)(LCD_BASE+0x5F4))
#define rLCD_LCD_COLOUR_MATRIX_REG3                     *((volatile unsigned int *)(LCD_BASE+0x5F8))
#define rLCD_LCD_COLOUR_MATRIX_REG4                     *((volatile unsigned int *)(LCD_BASE+0x5FC))
#define rLCD_LCD_COLOUR_MATRIX_REG5                     *((volatile unsigned int *)(LCD_BASE+0x600))

#define rLCD_TV_COLOUR_MATRIX_REG0                     	*((volatile unsigned int *)(LCD_BASE+0x604))
#define rLCD_TV_COLOUR_MATRIX_REG1                     	*((volatile unsigned int *)(LCD_BASE+0x608))
#define rLCD_TV_COLOUR_MATRIX_REG2                     	*((volatile unsigned int *)(LCD_BASE+0x60C))
#define rLCD_TV_COLOUR_MATRIX_REG3                     	*((volatile unsigned int *)(LCD_BASE+0x610))
#define rLCD_TV_COLOUR_MATRIX_REG4                     	*((volatile unsigned int *)(LCD_BASE+0x614))
#define rLCD_TV_COLOUR_MATRIX_REG5                     	*((volatile unsigned int *)(LCD_BASE+0x618))

#define rLCD_VIDEO1_COLOUR_MATRIX_REG0                  *((volatile unsigned int *)(LCD_BASE+0x61C))
#define rLCD_VIDEO1_COLOUR_MATRIX_REG1                  *((volatile unsigned int *)(LCD_BASE+0x620))
#define rLCD_VIDEO1_COLOUR_MATRIX_REG2                  *((volatile unsigned int *)(LCD_BASE+0x624))
#define rLCD_VIDEO1_COLOUR_MATRIX_REG3                  *((volatile unsigned int *)(LCD_BASE+0x628))
#define rLCD_VIDEO1_COLOUR_MATRIX_REG4                  *((volatile unsigned int *)(LCD_BASE+0x62C))
#define rLCD_VIDEO1_COLOUR_MATRIX_REG5                  *((volatile unsigned int *)(LCD_BASE+0x630))

#define rLCD_VIDEO2_COLOUR_MATRIX_REG0                  *((volatile unsigned int *)(LCD_BASE+0x634))
#define rLCD_VIDEO2_COLOUR_MATRIX_REG1                  *((volatile unsigned int *)(LCD_BASE+0x638))
#define rLCD_VIDEO2_COLOUR_MATRIX_REG2                  *((volatile unsigned int *)(LCD_BASE+0x63C))
#define rLCD_VIDEO2_COLOUR_MATRIX_REG3                  *((volatile unsigned int *)(LCD_BASE+0x640))
#define rLCD_VIDEO2_COLOUR_MATRIX_REG4                  *((volatile unsigned int *)(LCD_BASE+0x644))
#define rLCD_VIDEO2_COLOUR_MATRIX_REG5                  *((volatile unsigned int *)(LCD_BASE+0x648))

#define rLCD_OSD1_COLOUR_MATRIX_REG0                    *((volatile unsigned int *)(LCD_BASE+0x64C))
#define rLCD_OSD1_COLOUR_MATRIX_REG1                    *((volatile unsigned int *)(LCD_BASE+0x650))
#define rLCD_OSD1_COLOUR_MATRIX_REG2                    *((volatile unsigned int *)(LCD_BASE+0x654))
#define rLCD_OSD1_COLOUR_MATRIX_REG3                    *((volatile unsigned int *)(LCD_BASE+0x658))
#define rLCD_OSD1_COLOUR_MATRIX_REG4                    *((volatile unsigned int *)(LCD_BASE+0x65C))
#define rLCD_OSD1_COLOUR_MATRIX_REG5                    *((volatile unsigned int *)(LCD_BASE+0x660))

#define rLCD_OSD2_COLOUR_MATRIX_REG0                    *((volatile unsigned int *)(LCD_BASE+0x664))
#define rLCD_OSD2_COLOUR_MATRIX_REG1                    *((volatile unsigned int *)(LCD_BASE+0x668))
#define rLCD_OSD2_COLOUR_MATRIX_REG2                    *((volatile unsigned int *)(LCD_BASE+0x66C))
#define rLCD_OSD2_COLOUR_MATRIX_REG3                    *((volatile unsigned int *)(LCD_BASE+0x670))
#define rLCD_OSD2_COLOUR_MATRIX_REG4                    *((volatile unsigned int *)(LCD_BASE+0x674))
#define rLCD_OSD2_COLOUR_MATRIX_REG5                    *((volatile unsigned int *)(LCD_BASE+0x678))

#define rLCD_OSD3_COLOUR_MATRIX_REG0                    *((volatile unsigned int *)(LCD_BASE+0x67C))
#define rLCD_OSD3_COLOUR_MATRIX_REG1                    *((volatile unsigned int *)(LCD_BASE+0x680))
#define rLCD_OSD3_COLOUR_MATRIX_REG2                    *((volatile unsigned int *)(LCD_BASE+0x684))
#define rLCD_OSD3_COLOUR_MATRIX_REG3                    *((volatile unsigned int *)(LCD_BASE+0x688))
#define rLCD_OSD3_COLOUR_MATRIX_REG4                    *((volatile unsigned int *)(LCD_BASE+0x68C))
#define rLCD_OSD3_COLOUR_MATRIX_REG5                    *((volatile unsigned int *)(LCD_BASE+0x690))



/* GPIO */
#define rGPIO_PA_MOD					(*(volatile unsigned int *)(GPIO_BASE + 0x00))
#define rGPIO_PA_RDATA					(*(volatile unsigned int *)(GPIO_BASE + 0x04))
#define rGPIO_PA_INTEN					(*(volatile unsigned int *)(GPIO_BASE + 0x08))
#define rGPIO_PA_LEVEL					(*(volatile unsigned int *)(GPIO_BASE + 0x0C))
#define rGPIO_PA_PEND					(*(volatile unsigned int *)(GPIO_BASE + 0x10))

#define rGPIO_PB_MOD					(*(volatile unsigned int *)(GPIO_BASE + 0x20))
#define rGPIO_PB_RDATA					(*(volatile unsigned int *)(GPIO_BASE + 0x24))
#define rGPIO_PB_INTEN					(*(volatile unsigned int *)(GPIO_BASE + 0x28))
#define rGPIO_PB_LEVEL					(*(volatile unsigned int *)(GPIO_BASE + 0x2C))
#define rGPIO_PB_PEND					(*(volatile unsigned int *)(GPIO_BASE + 0x30))

#define rGPIO_PC_MOD					(*(volatile unsigned int *)(GPIO_BASE + 0x40))
#define rGPIO_PC_RDATA					(*(volatile unsigned int *)(GPIO_BASE + 0x44))
#define rGPIO_PC_INTEN					(*(volatile unsigned int *)(GPIO_BASE + 0x48))
#define rGPIO_PC_LEVEL					(*(volatile unsigned int *)(GPIO_BASE + 0x4C))
#define rGPIO_PC_PEND					(*(volatile unsigned int *)(GPIO_BASE + 0x50))

#define rGPIO_PD_MOD					(*(volatile unsigned int *)(GPIO_BASE + 0x60))
#define rGPIO_PD_RDATA					(*(volatile unsigned int *)(GPIO_BASE + 0x64))
#define rGPIO_PD_INTEN					(*(volatile unsigned int *)(GPIO_BASE + 0x68))
#define rGPIO_PD_LEVEL					(*(volatile unsigned int *)(GPIO_BASE + 0x6C))
#define rGPIO_PD_PEND					(*(volatile unsigned int *)(GPIO_BASE + 0x70))

#define rGPIO_DEBOUNCE_CNT_0				(*(volatile unsigned int *)(GPIO_BASE + 0x80))
#define rGPIO_DEBOUNCE_CNT_1				(*(volatile unsigned int *)(GPIO_BASE + 0x84))
#define rGPIO_DEBOUNCE_CNT_2				(*(volatile unsigned int *)(GPIO_BASE + 0x88))
#define rGPIO_DEBOUNCE_CNT_3				(*(volatile unsigned int *)(GPIO_BASE + 0x8c))
#define rGPIO_DEBOUNCE_CNT_4				(*(volatile unsigned int *)(GPIO_BASE + 0x90))
#define rGPIO_DEBOUNCE_CNT_5				(*(volatile unsigned int *)(GPIO_BASE + 0x94))
#define rGPIO_DEBOUNCE_CNT_6				(*(volatile unsigned int *)(GPIO_BASE + 0x98))
#define rGPIO_DEBOUNCE_CNT_7				(*(volatile unsigned int *)(GPIO_BASE + 0x9c))
#define rGPIO_DEBOUNCE_ENABLE				(*(volatile unsigned int *)(GPIO_BASE + 0xA0))



#endif /* ARK_SYS_H */
