# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux kernel.
#

# CPU-specific support
obj-$(CONFIG_SOC_ARK1668)		+= ark1668.o
obj-$(CONFIG_SOC_ARKN141)		+= arkn141.o
obj-$(CONFIG_SOC_ARK1668E)		+= ark1668e.o
obj-$(CONFIG_SOC_ARKN141S)		+= arkn141s.o
obj-$(CONFIG_SOC_AMT630H)		+= amt630h.o
obj-$(CONFIG_SMP)			+= headsmp.o platsmp.o

