LIBIMOBILEDEVICE_VERSION = 1.2.0
LIBIMOBILEDEVICE_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_ARK_PATH)/package/libimobiledevice/libimobiledevice-1.2.0
#LIBIMOBILEDEVICE_OVERRIDE_RSYNC = YES
LIBIMOBILEDEVICE_INSTALL_STAGING = YES
LIBIMOBILEDEVICE_INSTALL_TARGET = YES
LIBIMOBILEDEVICE_SITE_METHOD = local
LIBIMOBILEDEVICE_SITE = www.nomad-digital.com
LIBIMOBILEDEVICE_TARGET_INSTALL_STAGING = NO
#LIBIMOBILEDEVICE_AUTORECONF = YES
LIBIMOBILEDEVICE_DEPENDENCIES += libopenssl
LIBIMOBILEDEVICE_DEPENDENCIES += libplist
LIBIMOBILEDEVICE_DEPENDENCIES += libusbmuxd

#LIBIMOBILEDEVICE_CONF_ENV = \

LIBIMOBILEDEVICE_CONF_OPTS = \
	--enable-static \
	--disable-shared \
	--without-cython
#$(TARGET_CONFIGURE_OPTS) $(LIBIMOBILEDEVICE_CONF_ENV)
# the configure script is not generated by autoconf
define LIBIMOBILEDEVICE_CONFIGURE_CMDS
	(cd $(@D); ./configure \
		--prefix=/usr \
		--host="$(GNU_TARGET_NAME)" \
		$(LIBIMOBILEDEVICE_CONF_OPTS) \
		CC=$(TARGET_DIR)/../host/bin/arm-linux-gnueabihf-gcc \
		CXX=$(TARGET_DIR)/../host/bin/arm-linux-gnueabihf-gcc \
		openssl_CFLAGS="'-I$(STAGING_DIR)/usr/include/'" \
		openssl_LIBS="'-L$(STAGING_DIR)/usr/lib/ -lssl -lcrypto'" \
		libusbmuxd_CFLAGS="'-I$(STAGING_DIR)/usr/include/'" \
		libusbmuxd_LIBS="'-L$(STAGING_DIR)/usr/lib/ -lusbmuxd'" \
		libplist_CFLAGS="'-I$(STAGING_DIR)/usr/include/'" \
		libplist_LIBS="'-L$(STAGING_DIR)/usr/lib/ -lplist'" \
		libplistmm_CFLAGS="'-I$(STAGING_DIR)/usr/include/'" \
		libplistmm_LIBS="'-L$(STAGING_DIR)/usr/lib/ -lplistmm'" \
	)
endef


$(eval $(autotools-package)) 
