#
# Makefile: HX170DEC
#

obj-$(CONFIG_ARK_HX170DEC)	+= hx170dec.o 
obj-$(CONFIG_ARK_HX170DEC)	+= jpegdecapi.o jpegdechdrs.o jpegdecinternal.o jpegdecscan.o jpegdecutils.o regdrv.o dwl_linux.o dwl_linux_sc.o
