#
# Makefile: XS508
#

#obj-$(CONFIG_XS508)	+= xs508.o lib_XZS508_508A.o
#obj-$(CONFIG_XS508)	+= xs508.o lib_KYDZ508G_R1.o
#obj-$(CONFIG_XS508)	+= xs508.o lib_KYDZ508G_R1.hard.o
obj-$(CONFIG_XS508)	+= xs508.o lib_KYDZ508G_R1.softfp.o


