#!/bin/sh

start() {
	ubiattach /dev/ubi_ctrl -d 1 -m 9
	if  [ ! -d /data ];  then
	mkdir -p /data
	fi
	mount -o sync -t ubifs ubi1_0 /data
	if [ $? -eq 0 ]
	then
		echo "mount successfully!"
	else
		sync
		sleep 1
		mount -o sync -t ubifs ubi1_0 /data
		if [ $? -ne 0 ]
		then
			echo "mount failed! then reformat the volume!"
			ubidetach /dev/ubi_ctrl -m 9
			ubiformat /dev/mtd9
			ubiattach  /dev/ubi_ctrl -d 1 -m 9
			ubimkvol /dev/ubi1 -N data -m
			sleep 1
			mount -o sync -t ubifs ubi1_0 /data
			sync
		fi
	fi

	ifconfig lo up
	mdnsd&
	if  [ ! -f /data/carplay.ini ];  then
	cp -rf /etc/carplay.ini /data
	fi
	if  [ ! -f /data/auto.ini ];  then
	cp -rf /etc/auto.ini /data
	fi
}

stop() {
	echo "stop"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
