[default]

#生产厂商
manufacturer = arkmicro

#连接方式 0 ~ carplay, 1 ~ auto , 2 ~ carlife , 3 ~ hicar , 4 ~ eclink , 5 ~ mirror
link_mode = 0

#插入自动连接 0 ~ 不启动, 1 ~ 自动启动
auto_start = 0

#软件版本 
software_version = 1.0.0

#系统版本
os_version = 1.0.0

#自定义车机屏幕分辨率 0 ~ 用车机分辨率, 1 ~ 自定义车机分辨率 
diy_screen = 1

#在自定义车机屏幕分辨率生效  screen_offsetx: x坐标 , screen_offsety: y坐标 , screen_width: 宽度 , screen_height: 高度
screen_offsetx = 0
screen_offsety = 0
screen_width = 1920
screen_height = 720

#手机互联使用的usb端口 例如:usb_index= 0 表示 usb0 ,  usb_index=1 表示 usb1

usb_index = 0

#车机的蓝牙地址
bt_mac = 12:34:56:78:90:12

#加密芯片 0 ~ 不加密, 1 ~ 加密 
encryption = 1

[carplay]

#车机物理尺寸
screen_physical_width = 154
screen_physical_height = 87

#车机端回声消除时间间隔 
aec_delay = 50

#帧率
fps = 30

[carlife]

#安卓手机连接方式  android 0 ~ adb, 1 ~ aoa
android_link_mode = 0

#苹果连接方式  IOS 0 ~ EAP, 1 ~ USBMUX
ios_link_mode = 0

#手机端录音 0 ~ 车机录音, 1 ~ 手机录音
mic_record = 0

[auto]

[hicar]
[eclink]

#手机app版本 0 ~国内前装 ,1 ~国内后装 ,2 ~ 国外前装 , 3 ~ 国外后装

iphone_app = 0

[mirror]