LIBCHECK_VERSION = 1.0.10
LIBCHECK_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_ARK_PATH)/package/libcheck/check
#LIBCHECK_OVERRIDE_RSYNC = YES
LIBCHECK_INSTALL_STAGING = YES
LIBCHECK_INSTALL_TARGET = YES
LIBCHECK_SITE_METHOD = local
LIBCHECK_CONF_OPTS = --disable-shared
LIBCHECK_SITE = www.nomad-digital.com
LIBUSB_INSTALL_STAGING = YES

#LIBUSB_DEPENDENCIES += 
LIBCHECK_CONF_OPTS += --enable-static

$(eval $(autotools-package)) 
