#!/bin/bash
#-------------------------------------------------------------------------------
#-                                                                            --
#-       This software is confidential and proprietary and may be used        --
#-        only as expressly authorized by a licensing agreement from          --
#-                                                                            --
#-                            Hantro Products Oy.                             --
#-                                                                            --
#-                   (C) COPYRIGHT 2006 HANTRO PRODUCTS OY                    --
#-                            ALL RIGHTS RESERVED                             --
#-                                                                            --
#-                 The entire notice above must be reproduced                 --
#-                  on all copies and should not be removed.                  --
#-                                                                            --
#-------------------------------------------------------------------------------
#-
#--   Abstract     : Script for copying test scripts and binaries to
#                    test directory                                           --
#--                                                                           --
#-------------------------------------------------------------------------------

#=====--------------------------------------------------------------------=====#

cp ../../software/linux_reference/memalloc/memalloc.ko ../
cp ../../software/linux_reference/memalloc/memalloc_load.sh ../
cp ../../software/linux_reference/kernel_module/hx280enc.ko ../
cp ../../software/linux_reference/kernel_module/driver_load.sh ../
cp ../../software/linux_reference/test/h264/test_h264.sh ../
cp ../../software/linux_reference/test/h264/checkcase_h264.sh ../
cp ../../software/linux_reference/test/h264/checkall_h264.sh ../
cp ../../software/linux_reference/test/jpeg/test_jpeg.sh ../
cp ../../software/linux_reference/test/jpeg/checkcase_jpeg.sh ../
cp ../../software/linux_reference/test/jpeg/checkall_jpeg.sh ../
cp ../../software/linux_reference/test/camstab/test_vs.sh ../
cp ../../software/linux_reference/test/camstab/checkcase_vs.sh ../
cp ../../software/linux_reference/test/camstab/checkall_vs.sh ../
cp ../../software/linux_reference/test/common/f_check.sh ../
cp ../../software/linux_reference/test/common/f_run.sh ../
cp ../../software/linux_reference/test/common/hx170dec_pclinux ../
cp ../../software/linux_reference/test/common/hx170dec_pclinux_multifileoutput ../
cp ../../software/linux_reference/test/common/jx170dec_pclinux ../
cp ../../software/linux_reference/test/common/test_random_cases.sh ../
cp ../../software/linux_reference/test/common/checkall_random_cases.sh ../
cp ../../software/linux_reference/test/common/long_run_decode.sh ../
cp ../../software/linux_reference/test/common/long_run_encode.sh ..
