pcm.!dmix {
        type dmix
        ipc_key 6789
        ipc_key_add_uid yes
        slave {
                pcm "hw:0,1"
#               period_time 0
                period_size 4096
                buffer_size 16384
#               format S16_LE
#               rate 44100
        }
}
pcm.!dsnoop {
        type dsnoop
        ipc_key 5778
        ipc_key_add_uid yes
        slave {
                pcm "hw:0,0"
#               period_time 0
                period_size 4096
                buffer_size 16384
                channels 2
#               format S16_LE
#                rate 48000
        }
#        bindings.0 0
}

pcm.softvol {
    type            softvol
    slave {
        pcm         "dmix"      #redirect the output to dmix (instead of "hw:0,0")
    }
    control {
        name        "softmaster"       #override the PCM slider to set the softvol volume level globally
        card        0
    }
    min_dB            -51.0
    max_dB            -0.0
    resolution        128 
}
pcm.softvol1 {               
    type            softvol  
    slave {                     
        pcm         "dmix"      #redirect the output to dmix (instead of "hw:0,0")
    }                           
    control {                   
        name        "softmaster1"       #override the PCM slider to set the softvol volume level globally
        card        0           
    }                           
    min_dB            -51.0  
    max_dB            -0.0 
    resolution        128                                                         
}  
pcm.softvol2 {               
    type            softvol  
    slave {                     
        pcm         "dmix"      #redirect the output to dmix (instead of "hw:0,0")
    }                           
    control {                   
        name        "softmaster2"       #override the PCM slider to set the softvol volume level globally
        card        0           
    }                           
    min_dB            -51.0  
    max_dB            -0.0 
    resolution        128                                                         
}  
pcm.softvol3 {               
    type            softvol  
    slave {                     
        pcm         "dmix"      #redirect the output to dmix (instead of "hw:0,0")
    }                           
    control {                   
        name        "softmaster3"       #override the PCM slider to set the softvol volume level globally
        card        0           
    }                           
    min_dB            -51.0  
    max_dB            -0.0 
    resolution        128                                                         
}  
pcm.softvol4 {               
    type            softvol  
    slave {                     
        pcm         "dmix"      #redirect the output to dmix (instead of "hw:0,0")
    }                           
    control {                   
        name        "softmaster4"       #override the PCM slider to set the softvol volume level globally
        card        0           
    }                           
    min_dB            -51.0  
    max_dB            -0.0 
    resolution        128                                                         
}  
pcm.asymed {
        type asym
        playback.pcm "softvol"
        capture.pcm "dsnoop"
}

pcm.!default {
        type plug
        slave.pcm "asymed"
}

ctl.mixer0 {
        type hw
        card 0
}

