obj-$(CONFIG_FB_ARK1668LCD)      += ark1668_lcdfb.o ark1668_lcdc_funcs.o
obj-$(CONFIG_FB_ARKN141LCD)	     += arkn141_lcdfb.o arkn141_lcdc_funcs.o
obj-$(CONFIG_FB_ARK1668ELCD)	 += ark1668e_lcdfb.o ark1668e_lcdc_funcs.o
obj-$(CONFIG_FB_ARKN141SLCD)	 += arkn141s_lcdfb.o
