LIBUSBMUXD_VERSION = 1.0.10
LIBUSBMUXD_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_ARK_PATH)/package/libusbmuxd/libusbmuxd-1.0.10
#LIBUSBMUXD_OVERRIDE_RSYNC = YES
LIBUSBMUXD_INSTALL_STAGING = YES
LIBUSBMUXD_INSTALL_TARGET = YES
LIBUSBMUXD_SITE_METHOD = local
LIBUSBMUXD_CONF_OPTS = --disable-shared
LIBUSBMUXD_SITE = www.nomad-digital.com
LIBUSB_INSTALL_STAGING = YES

#LIBUSB_DEPENDENCIES += 
LIBUSBMUXD_CONF_OPTS += --enable-static

$(eval $(autotools-package)) 
