USBMUXD_VERSION = 1.0.10
USBMUXD_OVERRIDE_SRCDIR = $(BR2_EXTERNAL_ARK_PATH)/package/usbmuxd/usbmuxd-1.1.0
USBMUXD_OVERRIDE_RSYNC = YES
USBMUXD_INSTALL_STAGING = YES
USBMUXD_INSTALL_TARGET = YES
USBMUXD_SITE_METHOD = local
USBMUXD_CONF_OPTS = --disable-shared
USBMUXD_SITE = www.nomad-digital.com

USBMUXD_DEPENDENCIES += libusb
USBMUXD_DEPENDENCIES += libplist
USBMUXD_DEPENDENCIES += libimobiledevice
#LIBUSB_DEPENDENCIES += 
#LIBUSBMUXD_CONF_OPTS += --enable-static

$(eval $(autotools-package)) 
