#!/bin/sh

start() {
	if  [ ! -d /data ];  then
	mkdir -p /data
	fi

	fsck.ext4 -f -y /dev/mmcblk0p7
	mount /dev/mmcblk0p7 /data
	if [ $? -eq 0 ]
	then
		echo "mount successfully!"
	else
		sync
		sleep 1
		fsck.ext4 -f -y /dev/mmcblk0p7
		mount /dev/mmcblk0p7 /data
		if [ $? -ne 0 ]
		then
			echo "mount failed! then reformat the volume!"
			mkfs.ext4 -O ^64bit -O ^has_journal /dev/mmcblk0p7
			sleep 1
			mount /dev/mmcblk0p7 /data
			sync
		fi
	fi

	ifconfig lo up
	mdnsd&
	if  [ ! -f /data/carplay.ini ];  then
	cp -rf /etc/carplay.ini /data
	fi
	if  [ ! -f /data/auto.ini ];  then
	cp -rf /etc/auto.ini /data
	fi
}

stop() {
	echo "stop"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
