#ifndef ARK_SYS_H
#define	ARK_SYS_H

#define ARK_SYS_ADDR  SYS_BASE
/*
 * System register definitions
 */
#define rSYS_BOOT_SAMPLE	*((volatile unsigned int *)(SYS_BASE+0x0))
#define rSYS_CLK_SEL		*((volatile unsigned int *)(SYS_BASE+0x40))
#define rSYS_AHB_CLK_EN		*((volatile unsigned int *)(SYS_BASE+0x44))
#define rSYS_APB_CLK_EN		*((volatile unsigned int *)(SYS_BASE+0x48))
#define rSYS_AXI_CLK_EN		*((volatile unsigned int *)(SYS_BASE+0x4c))
#define rSYS_PER_CLK_EN		*((volatile unsigned int *)(SYS_BASE+0x50))
#define rSYS_LCD_CLK_CFG	*((volatile unsigned int *)(SYS_BASE+0x54))
#define rSYS_SD_CLK_CFG		*((volatile unsigned int *)(SYS_BASE+0x58))
#define rSYS_SD1_CLK_CFG	*((volatile unsigned int *)(SYS_BASE+0x5c))
#define rSYS_DEVICE_CLK_CFG0	*((volatile unsigned int *)(SYS_BASE+0x60))
#define rSYS_DEVICE_CLK_CFG1	*((volatile unsigned int *)(SYS_BASE+0x64))
#define rSYS_DEVICE_CLK_CFG2	*((volatile unsigned int *)(SYS_BASE+0x68)) 
#define rSYS_DEVICE_CLK_CFG3	*((volatile unsigned int *)(SYS_BASE+0x6c)) 

#define rSYS_CLK_DLY_REG	*((volatile unsigned int *)(SYS_BASE+0x70))
#define rSYS_SOFT_RSTNA		*((volatile unsigned int *)(SYS_BASE+0x74))
#define rSYS_SOFT_RSTNB		*((volatile unsigned int *)(SYS_BASE+0x78))
#define rSYS_SD2_CLK_CFG	*((volatile unsigned int *)(SYS_BASE+0x7c))

#define rSYS_ANALOG_REG0	*((volatile unsigned int *)(SYS_BASE+0x140))    
#define rSYS_ANALOG_REG1	*((volatile unsigned int *)(SYS_BASE+0x144))    
#define rSYS_DDR2_PAD_REG	*((volatile unsigned int *)(SYS_BASE+0x148))     
#define rSYS_PLLRFCK_CTL	*((volatile unsigned int *)(SYS_BASE+0x14c))    
#define rSYS_CPUPLL_CFG		*((volatile unsigned int *)(SYS_BASE+0x150))    
#define rSYS_SYSPLL_CFG		*((volatile unsigned int *)(SYS_BASE+0x154))    
#define rSYS_AUDPLL_CFG		*((volatile unsigned int *)(SYS_BASE+0x158))    
#define rSYS_DDRDLL_RDCLK_CFG	*((volatile unsigned int *)(SYS_BASE+0x15c))    
#define rSYS_DDRDLL_WRCLK_CFG	*((volatile unsigned int *)(SYS_BASE+0x160))    
#define rSYS_DDRDLL_DQS_CFG0	*((volatile unsigned int *)(SYS_BASE+0x164))
#define rSYS_DDRDLL_DQS_CFG1	*((volatile unsigned int *)(SYS_BASE+0x168))
#define rSYS_DDRDLL_DQS_CFG2	*((volatile unsigned int *)(SYS_BASE+0x16C))
#define rSYS_DDRDLL_BIAS_UP_TRIM	*((volatile unsigned int *)(SYS_BASE+0x170))
#define rSYS_DEVICE_CLK_CFG4	*((volatile unsigned int *)(SYS_BASE+0x174))

#define rSYS_LVDS_CTRL_CFG	*((volatile unsigned int *)(SYS_BASE+0x190))
#define rSYS_DDS_CLK_CFG	*((volatile unsigned int *)(SYS_BASE+0x198))
#define rSYS_DDS_IO_CFG		*((volatile unsigned int *)(SYS_BASE+0x19C))

#define rSYS_PAD_CTRL00		*((volatile unsigned int *)(SYS_BASE+0x1c0))
#define rSYS_PAD_CTRL01		*((volatile unsigned int *)(SYS_BASE+0x1c4))
#define rSYS_PAD_CTRL02		*((volatile unsigned int *)(SYS_BASE+0x1c8))
#define rSYS_PAD_CTRL03		*((volatile unsigned int *)(SYS_BASE+0x1cc))
#define rSYS_PAD_CTRL04		*((volatile unsigned int *)(SYS_BASE+0x1d0))
#define rSYS_PAD_CTRL05		*((volatile unsigned int *)(SYS_BASE+0x1d4))
#define rSYS_PAD_CTRL06		*((volatile unsigned int *)(SYS_BASE+0x1d8))
#define rSYS_PAD_CTRL07		*((volatile unsigned int *)(SYS_BASE+0x1dc))
#define rSYS_PAD_CTRL08		*((volatile unsigned int *)(SYS_BASE+0x1e0))
#define rSYS_PAD_CTRL09		*((volatile unsigned int *)(SYS_BASE+0x1e4))
#define rSYS_PAD_CTRL0A		*((volatile unsigned int *)(SYS_BASE+0x1e8))
#define rSYS_PAD_CTRL0B		*((volatile unsigned int *)(SYS_BASE+0x1ec))
#define rSYS_PAD_CTRL0C		*((volatile unsigned int *)(SYS_BASE+0x1f0))

/* PWM */
#define rPWM_ENA0                                       (*(volatile unsigned int *)(PWM_BASE + 0x00))
#define rPWM_DUTY0                                      (*(volatile unsigned int *)(PWM_BASE + 0x04))
#define rPWM_CNTR0                                      (*(volatile unsigned int *)(PWM_BASE + 0x08))
#define rPWM_ENA1                                       (*(volatile unsigned int *)(PWM_BASE + 0x10))
#define rPWM_DUTY1                                      (*(volatile unsigned int *)(PWM_BASE + 0x14))
#define rPWM_CNTR1                                      (*(volatile unsigned int *)(PWM_BASE + 0x18))
#define rPWM_ENA2                                       (*(volatile unsigned int *)(PWM_BASE + 0x20))
#define rPWM_DUTY2                                      (*(volatile unsigned int *)(PWM_BASE + 0x24))
#define rPWM_CNTR2                                      (*(volatile unsigned int *)(PWM_BASE + 0x28))
#define rPWM_ENA3                                       (*(volatile unsigned int *)(PWM_BASE + 0x30))
#define rPWM_DUTY3                                      (*(volatile unsigned int *)(PWM_BASE + 0x34))
#define rPWM_CNTR3                                      (*(volatile unsigned int *)(PWM_BASE + 0x38))
#define rPWM_ENA4                                       (*(volatile unsigned int *)(PWM_BASE + 0x40))
#define rPWM_DUTY4                                      (*(volatile unsigned int *)(PWM_BASE + 0x44))
#define rPWM_CNTR4                                      (*(volatile unsigned int *)(PWM_BASE + 0x48))
#define rPWM_ENA5                                       (*(volatile unsigned int *)(PWM_BASE + 0x50))
#define rPWM_DUTY5                                      (*(volatile unsigned int *)(PWM_BASE + 0x54))
#define rPWM_CNTR5                                      (*(volatile unsigned int *)(PWM_BASE + 0x58))

/* LCD */
#define rLCD_EANBLE										*((volatile unsigned int *)(LCD_BASE+0x000))
#define rLCD_CONTROL									*((volatile unsigned int *)(LCD_BASE+0x004))
#define rLCD_TIMING0									*((volatile unsigned int *)(LCD_BASE+0x008))
#define rLCD_TIMING1									*((volatile unsigned int *)(LCD_BASE+0x00c))
#define rLCD_TIMING2									*((volatile unsigned int *)(LCD_BASE+0x010))
#define rLCD_TIMING3									*((volatile unsigned int *)(LCD_BASE+0x014))
#define rLCD_TIMING_FRAME_START_CNT_LCD					*((volatile unsigned int *)(LCD_BASE+0x018))
#define rLCD_DITHERING									*((volatile unsigned int *)(LCD_BASE+0x020))
#define rLCD_ALPHA1_0_VIDEO_OSD1						*((volatile unsigned int *)(LCD_BASE+0x024))
#define rLCD_ALPHA1_0_OSD2_OSD3							*((volatile unsigned int *)(LCD_BASE+0x028))
#define rLCD_ALPHA1_0_VIDEO2							*((volatile unsigned int *)(LCD_BASE+0x030))
#define rLCD_VIDEO_BURST_CTL							*((volatile unsigned int *)(LCD_BASE+0x038))
#define rLCD_VIDEO_CTL									*((volatile unsigned int *)(LCD_BASE+0x03c))
#define rLCD_VIDEO_WIN_SIZE								*((volatile unsigned int *)(LCD_BASE+0x040))
#define rLCD_VIDEO_SIZE									*((volatile unsigned int *)(LCD_BASE+0x044))
#define rLCD_VIDEO_VIDEO2_BLD_COEF						*((volatile unsigned int *)(LCD_BASE+0x048))
#define rLCD_VIDEO_POSITION								*((volatile unsigned int *)(LCD_BASE+0x04c))
#define rLCD_BACK_COLOR									*((volatile unsigned int *)(LCD_BASE+0x050))
#define rLCD_VIDEO_ADDR1								*((volatile unsigned int *)(LCD_BASE+0x054))
#define rLCD_VIDEO_ADDR2								*((volatile unsigned int *)(LCD_BASE+0x058))
#define rLCD_VIDEO_ADDR3								*((volatile unsigned int *)(LCD_BASE+0x05c))
#define rLCD_BLD_MODE_LCD_REG0							*((volatile unsigned int *)(LCD_BASE+0x060))
#define rLCD_BLD_MODE_LCD_REG1							*((volatile unsigned int *)(LCD_BASE+0x064))
#define rLCD_BLD_MODE_TV_REG0							*((volatile unsigned int *)(LCD_BASE+0x068))
#define rLCD_BLD_MODE_TV_REG1							*((volatile unsigned int *)(LCD_BASE+0x06c))
#define rLCD_OSD1_BURST_CTL								*((volatile unsigned int *)(LCD_BASE+0x070))
#define rLCD_OSD1_CTL									*((volatile unsigned int *)(LCD_BASE+0x074))
#define rLCD_OSD1_SIZE									*((volatile unsigned int *)(LCD_BASE+0x078))
#define rLCD_OSD1_POSITION								*((volatile unsigned int *)(LCD_BASE+0x07c))
#define rLCD_OSD1_ADDR									*((volatile unsigned int *)(LCD_BASE+0x080))
#define rLCD_OSD2_BURST_CTL								*((volatile unsigned int *)(LCD_BASE+0x084))
#define rLCD_OSD2_CTL									*((volatile unsigned int *)(LCD_BASE+0x088))
#define rLCD_OSD2_SIZE									*((volatile unsigned int *)(LCD_BASE+0x08c))
#define rLCD_OSD2_POSITION								*((volatile unsigned int *)(LCD_BASE+0x090))
#define rLCD_OSD2_ADDR									*((volatile unsigned int *)(LCD_BASE+0x094))                                  
#define rLCD_OSD3_CTL									*((volatile unsigned int *)(LCD_BASE+0x098))
#define rLCD_OSD3_SIZE									*((volatile unsigned int *)(LCD_BASE+0x09c))
#define rLCD_OSD3_POSITION								*((volatile unsigned int *)(LCD_BASE+0x0a0))
#define rLCD_OSD3_ADDR									*((volatile unsigned int *)(LCD_BASE+0x0a4))
#define rLCD_OSD3_BURST_CTL								*((volatile unsigned int *)(LCD_BASE+0x0a8))
#define rLCD_VIDEO_SCALE_VXMOD							*((volatile unsigned int *)(LCD_BASE+0x0ac))
#define rLCD_VIDEO_SCALE_CTL							*((volatile unsigned int *)(LCD_BASE+0x0b0))
#define rLCD_VIDEO_SCAL_CTL0							*((volatile unsigned int *)(LCD_BASE+0x0b4))
#define rLCD_VIDEO_SCAL_CTL1							*((volatile unsigned int *)(LCD_BASE+0x0b8))
#define rLCD_VIDEO_RIGHT_BOTTOM_CUT_NUM					*((volatile unsigned int *)(LCD_BASE+0x0bc))
#define rLCD_VIDEO_SCAL_CTL2							*((volatile unsigned int *)(LCD_BASE+0x0c0))
#define rLCD_VIDEO_SCAL_CTL3							*((volatile unsigned int *)(LCD_BASE+0x0c4))
#define rLCD_VIDEO_SCAL_CTL4							*((volatile unsigned int *)(LCD_BASE+0x0c8))
#define rLCD_VIDEO_HSCAL_COS_VALUE						*((volatile unsigned int *)(LCD_BASE+0x0cc))
#define rLCD_COLOR_KEY_MASK_THLD_VIDEO					*((volatile unsigned int *)(LCD_BASE+0x0d8))
#define rLCD_COLOR_KEY_MASK_THLD_OSD1					*((volatile unsigned int *)(LCD_BASE+0x0dc))
#define rLCD_COLOR_KEY_MASK_THLD_OSD2					*((volatile unsigned int *)(LCD_BASE+0x0e0))
#define rLCD_COLOR_KEY_MASK_THLD_OSD3					*((volatile unsigned int *)(LCD_BASE+0x0e4))
#define rLCD_COLOR_KEY_MASK_VALUE_VIDEO					*((volatile unsigned int *)(LCD_BASE+0x0e8))
#define rLCD_COLOR_KEY_MASK_VALUE_OSD1					*((volatile unsigned int *)(LCD_BASE+0x0ec))
#define rLCD_COLOR_KEY_MASK_VALUE_OSD2					*((volatile unsigned int *)(LCD_BASE+0x0f0))
#define rLCD_COLOR_KEY_MASK_VALUE_OSD3					*((volatile unsigned int *)(LCD_BASE+0x0f4))
#define CLCD_BLD_CUT_LEFT_RIGHT_VIDEO					*((volatile unsigned int *)(LCD_BASE+0x0fc))
#define rLCD_BLD_CUT_UP_DOWN_VIDEO						*((volatile unsigned int *)(LCD_BASE+0x100))
#define rLCD_BLD_CUT_LEFT_RIGHT_OSD1					*((volatile unsigned int *)(LCD_BASE+0x104))
#define rLCD_BLD_CUT_UP_DOWN_OSD1						*((volatile unsigned int *)(LCD_BASE+0x108))
#define rLCD_BLD_CUT_LEFT_RIGHT_OSD2					*((volatile unsigned int *)(LCD_BASE+0x10c))
#define rLCD_BLD_CUT_UP_DOWN_OSD2						*((volatile unsigned int *)(LCD_BASE+0x110))
#define rLCD_BLD_CUT_LEFT_RIGHT_OSD3					*((volatile unsigned int *)(LCD_BASE+0x114))
#define rLCD_BLD_CUT_UP_DOWN_OSD3						*((volatile unsigned int *)(LCD_BASE+0x118))
#define rLCD_Y2R_COEF321								*((volatile unsigned int *)(LCD_BASE+0x11c))
#define rLCD_Y2R_COEF654								*((volatile unsigned int *)(LCD_BASE+0x120))
#define rLCD_Y2R_COEF7									*((volatile unsigned int *)(LCD_BASE+0x124))
#define rLCD_VIDEO2_VP_REG_0							*((volatile unsigned int *)(LCD_BASE+0x130))
#define rLCD_VIDEO2_VP_REG_1							*((volatile unsigned int *)(LCD_BASE+0x134))
#define rLCD_VIDEO2_VP_REG_2							*((volatile unsigned int *)(LCD_BASE+0x138))
#define rLCD_VIDEO2_VP_REG_3							*((volatile unsigned int *)(LCD_BASE+0x13c)) 
#define rLCD_VIDEO2_VP_REG_4							*((volatile unsigned int *)(LCD_BASE+0x140))
#define rLCD_OSD1_VP_REG_1								*((volatile unsigned int *)(LCD_BASE+0x144))
#define rLCD_OSD1_VP_REG_2								*((volatile unsigned int *)(LCD_BASE+0x148))
#define rLCD_OSD2_VP_REG_1								*((volatile unsigned int *)(LCD_BASE+0x14c)) 
#define rLCD_OSD2_VP_REG_2								*((volatile unsigned int *)(LCD_BASE+0x150))
#define rLCD_OSD3_VP_REG_1								*((volatile unsigned int *)(LCD_BASE+0x154)) 
#define rLCD_OSD3_VP_REG_2								*((volatile unsigned int *)(LCD_BASE+0x158)) 
#define rLCD_VIDEO_WIN_POINT							*((volatile unsigned int *)(LCD_BASE+0x15C))
#define rLCD_OSD1_WIN_POINT								*((volatile unsigned int *)(LCD_BASE+0x160))
#define rLCD_OSD2_WIN_POINT								*((volatile unsigned int *)(LCD_BASE+0x164))
#define rLCD_OSD3_WIN_POINT								*((volatile unsigned int *)(LCD_BASE+0x168)) 
#define rLCD_VIDEO_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x16c)) 
#define rLCD_OSD1_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x170)) 
#define rLCD_OSD2_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x174)) 
#define rLCD_OSD3_SOURCE_SIZE							*((volatile unsigned int *)(LCD_BASE+0x178)) 
#define rLCD_INTERRUPT_CTL								*((volatile unsigned int *)(LCD_BASE+0x17c))
#define rLCD_INTERRUPT_STATUS							*((volatile unsigned int *)(LCD_BASE+0x180))
#define rLCD_TIMING_INIT								*((volatile unsigned int *)(LCD_BASE+0x184))

#define rLCD_TCON_REG0									*((volatile unsigned int *)(LCD_BASE+0x188))	
#define rLCD_TCON_REG1									*((volatile unsigned int *)(LCD_BASE+0x18c))
#define rLCD_TCON_REG2									*((volatile unsigned int *)(LCD_BASE+0x190))
#define rLCD_TCON_REG3									*((volatile unsigned int *)(LCD_BASE+0x194))
#define rLCD_TCON_REG4									*((volatile unsigned int *)(LCD_BASE+0x198))
#define rLCD_TCON_REG5									*((volatile unsigned int *)(LCD_BASE+0x19c))
#define rLCD_TCON_REG6									*((volatile unsigned int *)(LCD_BASE+0x1a0))
#define rLCD_TCON_REG7									*((volatile unsigned int *)(LCD_BASE+0x1a4))
#define rLCD_TCON_REG8									*((volatile unsigned int *)(LCD_BASE+0x1a8))
#define rLCD_TCON_REG9									*((volatile unsigned int *)(LCD_BASE+0x1ac))
#define rLCD_TCON_REG10									*((volatile unsigned int *)(LCD_BASE+0x1b0))
#define rLCD_TCON_REG11									*((volatile unsigned int *)(LCD_BASE+0x1b4))
#define rLCD_TCON_REG12									*((volatile unsigned int *)(LCD_BASE+0x1b8))
#define rLCD_TCON_REG13									*((volatile unsigned int *)(LCD_BASE+0x1bc))
#define rLCD_TCON_REG14									*((volatile unsigned int *)(LCD_BASE+0x1c0))
#define rLCD_TCON_REG15									*((volatile unsigned int *)(LCD_BASE+0x1c4))
#define rLCD_TCON_REG16									*((volatile unsigned int *)(LCD_BASE+0x1c8))
#define rLCD_TCON_REG17									*((volatile unsigned int *)(LCD_BASE+0x1cc))
#define rLCD_TCON_REG18									*((volatile unsigned int *)(LCD_BASE+0x1d0))
										
#define rLCD_VIDEO_VP_REG_0								*((volatile unsigned int *)(LCD_BASE+0x1d4))
#define rLCD_VIDEO_VP_REG_1								*((volatile unsigned int *)(LCD_BASE+0x1d8))
#define rLCD_VIDEO_VP_REG_2								*((volatile unsigned int *)(LCD_BASE+0x1dc))
#define rLCD_VIDEO_VP_REG_3								*((volatile unsigned int *)(LCD_BASE+0x1e0))
#define rLCD_VIDEO_VP_REG_4								*((volatile unsigned int *)(LCD_BASE+0x1e4))
                                 
#define rLCD_GAMMA_REG_0								*((volatile unsigned int *)(LCD_BASE+0x1ec))
#define rLCD_GAMMA_REG_1								*((volatile unsigned int *)(LCD_BASE+0x1f0))
#define rLCD_GAMMA_REG_2								*((volatile unsigned int *)(LCD_BASE+0x1f4))
#define rLCD_GAMMA_REG_3								*((volatile unsigned int *)(LCD_BASE+0x1f8))
#define rLCD_GAMMA_REG_4								*((volatile unsigned int *)(LCD_BASE+0x1fc))
#define rLCD_GAMMA_REG_5								*((volatile unsigned int *)(LCD_BASE+0x200))
#define rLCD_GAMMA_REG_6								*((volatile unsigned int *)(LCD_BASE+0x204))
#define rLCD_GAMMA_REG_7								*((volatile unsigned int *)(LCD_BASE+0x208))
#define rLCD_GAMMA_REG_8								*((volatile unsigned int *)(LCD_BASE+0x20c))
#define rLCD_GAMMA_REG_9								*((volatile unsigned int *)(LCD_BASE+0x210))
#define rLCD_GAMMA_REG_10								*((volatile unsigned int *)(LCD_BASE+0x214))
#define rLCD_GAMMA_REG_11								*((volatile unsigned int *)(LCD_BASE+0x218))
#define rLCD_GAMMA_REG_12								*((volatile unsigned int *)(LCD_BASE+0x21c))
#define rLCD_GAMMA_REG_13								*((volatile unsigned int *)(LCD_BASE+0x220))
#define rLCD_GAMMA_REG_14								*((volatile unsigned int *)(LCD_BASE+0x224))
#define rLCD_GAMMA_REG_15								*((volatile unsigned int *)(LCD_BASE+0x228))
#define rLCD_GAMMA_REG_16								*((volatile unsigned int *)(LCD_BASE+0x22c))
#define rLCD_GAMMA_REG_17								*((volatile unsigned int *)(LCD_BASE+0x230))
#define rLCD_GAMMA_REG_18								*((volatile unsigned int *)(LCD_BASE+0x234))
#define rLCD_GAMMA_REG_19								*((volatile unsigned int *)(LCD_BASE+0x238))
#define rLCD_GAMMA_REG_20								*((volatile unsigned int *)(LCD_BASE+0x23c))
#define rLCD_GAMMA_REG_21								*((volatile unsigned int *)(LCD_BASE+0x240))
#define rLCD_GAMMA_REG_22								*((volatile unsigned int *)(LCD_BASE+0x244))
#define rLCD_GAMMA_REG_23								*((volatile unsigned int *)(LCD_BASE+0x248))
#define rLCD_GAMMA_REG_24								*((volatile unsigned int *)(LCD_BASE+0x24c))
#define rLCD_GAMMA_REG_25								*((volatile unsigned int *)(LCD_BASE+0x250))
#define rLCD_GAMMA_REG_26								*((volatile unsigned int *)(LCD_BASE+0x254))
#define rLCD_GAMMA_REG_27								*((volatile unsigned int *)(LCD_BASE+0x258))
#define rLCD_GAMMA_REG_28								*((volatile unsigned int *)(LCD_BASE+0x25c))
#define rLCD_GAMMA_REG_29								*((volatile unsigned int *)(LCD_BASE+0x260))
#define rLCD_GAMMA_REG_30								*((volatile unsigned int *)(LCD_BASE+0x264))
#define rLCD_GAMMA_REG_31								*((volatile unsigned int *)(LCD_BASE+0x268))
#define rLCD_GAMMA_REG_32								*((volatile unsigned int *)(LCD_BASE+0x26c))
#define rLCD_GAMMA_REG_33								*((volatile unsigned int *)(LCD_BASE+0x270))
#define rLCD_GAMMA_REG_34								*((volatile unsigned int *)(LCD_BASE+0x274))
#define rLCD_GAMMA_REG_35								*((volatile unsigned int *)(LCD_BASE+0x278))
#define rLCD_GAMMA_REG_36								*((volatile unsigned int *)(LCD_BASE+0x27c))
#define rLCD_GAMMA_REG_37								*((volatile unsigned int *)(LCD_BASE+0x280))
#define rLCD_GAMMA_REG_38								*((volatile unsigned int *)(LCD_BASE+0x284))
#define rLCD_GAMMA_REG_39								*((volatile unsigned int *)(LCD_BASE+0x288))
#define rLCD_GAMMA_REG_40								*((volatile unsigned int *)(LCD_BASE+0x28c))
#define rLCD_GAMMA_REG_41								*((volatile unsigned int *)(LCD_BASE+0x290))
#define rLCD_GAMMA_REG_42								*((volatile unsigned int *)(LCD_BASE+0x294))
#define rLCD_GAMMA_REG_43								*((volatile unsigned int *)(LCD_BASE+0x298))
#define rLCD_GAMMA_REG_44								*((volatile unsigned int *)(LCD_BASE+0x29c))
#define rLCD_GAMMA_REG_45								*((volatile unsigned int *)(LCD_BASE+0x2a0))
#define rLCD_GAMMA_REG_46								*((volatile unsigned int *)(LCD_BASE+0x2a4))
#define rLCD_GAMMA_REG_47								*((volatile unsigned int *)(LCD_BASE+0x2a8))
#define rLCD_GAMMA_REG_48								*((volatile unsigned int *)(LCD_BASE+0x2ac))
//TV ENCODER
#define rLCD_TV_CONTROL                 				*((volatile unsigned int *)(LCD_BASE+0x2b0))
#define rLCD_TIMING0_TV                 				*((volatile unsigned int *)(LCD_BASE+0x2b4))
#define rLCD_TIMING1_TV                 				*((volatile unsigned int *)(LCD_BASE+0x2b8))
#define rLCD_TIMING2_TV                 				*((volatile unsigned int *)(LCD_BASE+0x2bc))
#define rLCD_TIMING3_TV                 				*((volatile unsigned int *)(LCD_BASE+0x2c0))
#define rLCD_TIMING_FRAME_START_CNT_TV  				*((volatile unsigned int *)(LCD_BASE+0x2c4))
#define rTU656_TIMING_TIMING_CNT_NUMBER 				*((volatile unsigned int *)(LCD_BASE+0x2c8))
#define rLCD_BACK_COLOR_TV              				*((volatile unsigned int *)(LCD_BASE+0x2cc))
#define rLCD_Y2R_COEF321_TV             				*((volatile unsigned int *)(LCD_BASE+0x2d0))
#define rLCD_Y2R_COEF654_TV             				*((volatile unsigned int *)(LCD_BASE+0x2d4))
#define rLCD_Y2R_COEF7_TV              	 				*((volatile unsigned int *)(LCD_BASE+0x2d8))

#define rLCD_VIDEO_ADDR1_GROUP1         				*((volatile unsigned int *)(LCD_BASE+0x2e4))
#define rLCD_VIDEO_ADDR2_GROUP1         				*((volatile unsigned int *)(LCD_BASE+0x2e8))
#define rLCD_VIDEO_ADDR3_GROUP1         				*((volatile unsigned int *)(LCD_BASE+0x2ec))
#define rLCD_OSD1_ADDR_GROUP1           				*((volatile unsigned int *)(LCD_BASE+0x2f0))
#define rLCD_OSD2_ADDR_GROUP1           				*((volatile unsigned int *)(LCD_BASE+0x2f4))
#define rLCD_OSD3_ADDR_GROUP1           				*((volatile unsigned int *)(LCD_BASE+0x2f8))

#define rLCD_EXCTRL1                    				*((volatile unsigned int *)(LCD_BASE+0x2fc))
#define rLCD_EXCTRL2                    				*((volatile unsigned int *)(LCD_BASE+0x300))
#define rLCD_YPBPR_CTRL0                				*((volatile unsigned int *)(LCD_BASE+0x304))
#define rLCD_YPBPR_CTRL1                				*((volatile unsigned int *)(LCD_BASE+0x308))
#define rLCD_YPBPR_CTRL2                				*((volatile unsigned int *)(LCD_BASE+0x30c))
#define rLCD_YPBPR_CTRL3                				*((volatile unsigned int *)(LCD_BASE+0x310))
#define rLCD_YPBPR_CTRL4                				*((volatile unsigned int *)(LCD_BASE+0x314))
#define rLCD_YPBPR_CTRL5                				*((volatile unsigned int *)(LCD_BASE+0x318))
#define rLCD_VIDEO2_BURST_CTL           				*((volatile unsigned int *)(LCD_BASE+0x31c))
#define rLCD_VIDEO2_CTL                 				*((volatile unsigned int *)(LCD_BASE+0x320))
#define rLCD_VIDEO2_SOURCE_SIZE         				*((volatile unsigned int *)(LCD_BASE+0x324))
#define rLCD_VIDEO2_WIN_POINT           				*((volatile unsigned int *)(LCD_BASE+0x328))
#define rLCD_VIDEO2_WIN_SIZE            				*((volatile unsigned int *)(LCD_BASE+0x32c))
#define rLCD_VIDEO2_SIZE                				*((volatile unsigned int *)(LCD_BASE+0x330))
#define rLCD_VIDEO2_POSITION            				*((volatile unsigned int *)(LCD_BASE+0x334))
#define rLCD_VIDEO2_ADDR1               				*((volatile unsigned int *)(LCD_BASE+0x338))
#define rLCD_VIDEO2_ADDR2               				*((volatile unsigned int *)(LCD_BASE+0x33c))
#define rLCD_VIDEO2_ADDR3               				*((volatile unsigned int *)(LCD_BASE+0x340))
#define rLCD_VIDEO2_ADDR1_GROUP1        				*((volatile unsigned int *)(LCD_BASE+0x344))
#define rLCD_VIDEO2_ADDR2_GROUP1        				*((volatile unsigned int *)(LCD_BASE+0x348))
#define rLCD_VIDEO2_ADDR3_GROUP1        				*((volatile unsigned int *)(LCD_BASE+0x34c))
#define rLCD_VIDEO2_SCALE_VXMOD         				*((volatile unsigned int *)(LCD_BASE+0x350))
#define rLCD_VIDEO2_SCALE_CTL           				*((volatile unsigned int *)(LCD_BASE+0x354))
#define rLCD_VIDEO2_SCAL_CTL0           				*((volatile unsigned int *)(LCD_BASE+0x358))
#define rLCD_VIDEO2_SCAL_CTL1           				*((volatile unsigned int *)(LCD_BASE+0x35c))
#define rLCD_VIDEO2_RIGHT_BOTTOM_CUT_NUM    			*((volatile unsigned int *)(LCD_BASE+0x360))
#define rLCD_VIDEO2_SCAL_CTL2               			*((volatile unsigned int *)(LCD_BASE+0x364))
#define rLCD_VIDEO2_SCAL_CTL3               			*((volatile unsigned int *)(LCD_BASE+0x368))
#define rLCD_VIDEO2_SCAL_CTL4               			*((volatile unsigned int *)(LCD_BASE+0x36c))
#define rLCD_VIDEO2_HSCAL_COS_VALUE         			*((volatile unsigned int *)(LCD_BASE+0x370))
#define rLCD_COLOR_KEY_MASK_THLD_VIDEO2     			*((volatile unsigned int *)(LCD_BASE+0x374))
#define rLCD_COLOR_KEY_MASK_VALUE_VIDEO2    			*((volatile unsigned int *)(LCD_BASE+0x378))
#define rLCD_BLD_CUT_LEFT_RIGHT_VIDEO2      			*((volatile unsigned int *)(LCD_BASE+0x37c))
#define rLCD_BLD_CUT_UP_DOWN_VIDEO2         			*((volatile unsigned int *)(LCD_BASE+0x380))
#define rLCD_WRITE_BACK_ADDR_VIDEO2         			*((volatile unsigned int *)(LCD_BASE+0x384))
#define rLCD_WB_DATA_PER_FRAME_VIDEO2       			*((volatile unsigned int *)(LCD_BASE+0x388))

#define rLCD_TV_HV_DELAY                				*((volatile unsigned int *)(LCD_BASE+0x3ac))
#define rLCD_TV_ENCODER_REG00           				*((volatile unsigned int *)(LCD_BASE+0x3b0))
#define rLCD_TV_ENCODER_REG01           				*((volatile unsigned int *)(LCD_BASE+0x3b4))
#define rLCD_TV_ENCODER_REG02           				*((volatile unsigned int *)(LCD_BASE+0x3b8))
#define rLCD_TV_ENCODER_REG03           				*((volatile unsigned int *)(LCD_BASE+0x3bc))
#define rLCD_TV_ENCODER_REG04           				*((volatile unsigned int *)(LCD_BASE+0x3c0))
#define rLCD_COLOR_MATRIX_REG00         				*((volatile unsigned int *)(LCD_BASE+0x3c4))
#define rLCD_COLOR_MATRIX_REG01         				*((volatile unsigned int *)(LCD_BASE+0x3c8))
#define rLCD_COLOR_MATRIX_REG02         				*((volatile unsigned int *)(LCD_BASE+0x3cc))
#define rLCD_ITU656_BYP_MOD_CTL         				*((volatile unsigned int *)(LCD_BASE+0x3d0))
#define rLCD_ITU656_BYP_MOD_NTSC_REG0  				 	*((volatile unsigned int *)(LCD_BASE+0x3d4))
#define rLCD_ITU656_BYP_MOD_NTSC_REG1   				*((volatile unsigned int *)(LCD_BASE+0x3d8))
#define rLCD_ITU656_BYP_MOD_NTSC_REG2   				*((volatile unsigned int *)(LCD_BASE+0x3dc))
#define rLCD_ITU656_BYP_MOD_NTSC_REG3   				*((volatile unsigned int *)(LCD_BASE+0x3e0))
#define rLCD_ITU656_BYP_MOD_NTSC_REG4   				*((volatile unsigned int *)(LCD_BASE+0x3e4))
#define rLCD_ITU656_BYP_MOD_PAL_REG0    				*((volatile unsigned int *)(LCD_BASE+0x3e8))
#define rLCD_ITU656_BYP_MOD_PAL_REG1    				*((volatile unsigned int *)(LCD_BASE+0x3ec))
#define rLCD_ITU656_BYP_MOD_PAL_REG2    				*((volatile unsigned int *)(LCD_BASE+0x3f0))
#define rLCD_ITU656_BYP_MOD_PAL_REG3    				*((volatile unsigned int *)(LCD_BASE+0x3f4))
#define rLCD_ITU656_BYP_MOD_PAL_REG4    				*((volatile unsigned int *)(LCD_BASE+0x3f8))
#define rLCD_ITU656_BYP_MOD_REG0        				*((volatile unsigned int *)(LCD_BASE+0x3fc))

#define rLCD_Palette_BASE   (volatile unsigned int *)(ark_lcd_mmio_base+0x400)

#define rLCD_TV_PARAM_REG0								*((volatile unsigned int *)(LCD_BASE+0x800))
#define rLCD_TV_PARAM_REG1								*((volatile unsigned int *)(LCD_BASE+0x804))
#define rLCD_TV_PARAM_REG2								*((volatile unsigned int *)(LCD_BASE+0x808))
#define rLCD_TV_PARAM_REG3								*((volatile unsigned int *)(LCD_BASE+0x80C))
#define rLCD_TV_PARAM_REG4								*((volatile unsigned int *)(LCD_BASE+0x810))			
#define rLCD_TV_PARAM_REG5								*((volatile unsigned int *)(LCD_BASE+0x814))	
#define rLCD_TV_PARAM_REG6								*((volatile unsigned int *)(LCD_BASE+0x818))
#define rLCD_TV_PARAM_REG7								*((volatile unsigned int *)(LCD_BASE+0x81c))
#define rLCD_TV_PARAM_REG8								*((volatile unsigned int *)(LCD_BASE+0x820))
#define rLCD_TV_PARAM_REG9								*((volatile unsigned int *)(LCD_BASE+0x824))
#define rLCD_TV_PARAM_REG10							*((volatile unsigned int *)(LCD_BASE+0x828))
#define rLCD_TV_PARAM_REG11							*((volatile unsigned int *)(LCD_BASE+0x82C))
#define rLCD_TV_PARAM_REG12							*((volatile unsigned int *)(LCD_BASE+0x830))
#define rLCD_TV_PARAM_REG13							*((volatile unsigned int *)(LCD_BASE+0x834))
#define rLCD_TV_PARAM_REG14							*((volatile unsigned int *)(LCD_BASE+0x838))
#define rLCD_TV_PARAM_REG15							*((volatile unsigned int *)(LCD_BASE+0x83C))
#define rLCD_TV_PARAM_REG16							*((volatile unsigned int *)(LCD_BASE+0x840))
#define rLCD_TV_PARAM_REG17							*((volatile unsigned int *)(LCD_BASE+0x844))
#define rLCD_TV_PARAM_REG18							*((volatile unsigned int *)(LCD_BASE+0x848))
#define rLCD_TV_PARAM_REG19							*((volatile unsigned int *)(LCD_BASE+0x84C))
#define rLCD_TV_PARAM_REG20							*((volatile unsigned int *)(LCD_BASE+0x850))
#define rLCD_TV_PARAM_REG21							*((volatile unsigned int *)(LCD_BASE+0x854))

/* ITU656 */
#define rITU656IN_MODULE_EN								*((volatile unsigned int *)(ITU656IN_BASE+0x000)) 
#define rITU656IN_IMR									*((volatile unsigned int *)(ITU656IN_BASE+0x124))
#define rITU656IN_ICR									*((volatile unsigned int *)(ITU656IN_BASE+0x128))
#define rITU656IN_ISR									*((volatile unsigned int *)(ITU656IN_BASE+0x12C))
#define rITU656IN_LINE_NUM_PER_FIELD					*((volatile unsigned int *)(ITU656IN_BASE+0x8f4))
#define rITU656IN_PIX_NUM_PER_LINE						*((volatile unsigned int *)(ITU656IN_BASE+0x8f8))
#define PIX_LINE_NUM_DELTA								*((volatile unsigned int *)(ITU656IN_BASE+0x8fc))

#define rITU656IN_INPUT_SEL								*((volatile unsigned int *)(ITU656IN_BASE+0x900))
#define rITU656IN_SEP_MODE_SEL							*((volatile unsigned int *)(ITU656IN_BASE+0x904))
#define rITU656IN_H_STRAT								*((volatile unsigned int *)(ITU656IN_BASE+0x908))
#define rITU656IN_H_END									*((volatile unsigned int *)(ITU656IN_BASE+0x90C))
#define rITU656IN_H_WIDTH								*((volatile unsigned int *)(ITU656IN_BASE+0x910))
#define rITU656IN_V_START_0								*((volatile unsigned int *)(ITU656IN_BASE+0x914))
#define rITU656IN_V_END_0								*((volatile unsigned int *)(ITU656IN_BASE+0x918))
#define rITU656IN_V_START_1								*((volatile unsigned int *)(ITU656IN_BASE+0x91C))
#define rITU656IN_V_END_1								*((volatile unsigned int *)(ITU656IN_BASE+0x920))
#define rITU656IN_V_FIELD_0								*((volatile unsigned int *)(ITU656IN_BASE+0x924))
#define rITU656IN_V_FIELD_1								*((volatile unsigned int *)(ITU656IN_BASE+0x928))
#define rITU656IN_P_N_DETECT							*((volatile unsigned int *)(ITU656IN_BASE+0x92C))
#define rITU656IN_ENABLE_REG							*((volatile unsigned int *)(ITU656IN_BASE+0x930)) 
#define rITU656IN_SIZE									*((volatile unsigned int *)(ITU656IN_BASE+0x938)) 
#define rITU656IN_TOTAL_PIX								*((volatile unsigned int *)(ITU656IN_BASE+0x94C))
#define rITU656IN_DRAM_DEST1							*((volatile unsigned int *)(ITU656IN_BASE+0x950))
#define rITU656IN_DRAM_DEST2							*((volatile unsigned int *)(ITU656IN_BASE+0x954))
#define rITU656IN_DATA_OUT_NUM							*((volatile unsigned int *)(ITU656IN_BASE+0x958))
#define rITU656IN_OUTLINE_NUM_PER_FIELD					*((volatile unsigned int *)(ITU656IN_BASE+0x95c))


//JPEG
#define rJPEG_0                                   					*((volatile unsigned int *)(JPEG_BASE+0x00))
#define rJPEG_1                                   					*((volatile unsigned int *)(JPEG_BASE+0x04))
#define rJPEG_2                                   					*((volatile unsigned int *)(JPEG_BASE+0x08))
#define rJPEG_3                                   					*((volatile unsigned int *)(JPEG_BASE+0x0C))
#define rJPEG_4                                   					*((volatile unsigned int *)(JPEG_BASE+0x10))
#define rJPEG_5                                   					*((volatile unsigned int *)(JPEG_BASE+0x14))
#define rJPEG_6                                   					*((volatile unsigned int *)(JPEG_BASE+0x18))
#define rJPEG_7                                   					*((volatile unsigned int *)(JPEG_BASE+0x1C))
#define rJPEG_STATUS                              					*((volatile unsigned int *)(JPEG_BASE+0x20))
#define rJPEG_WRSTA                               					*((volatile unsigned int *)(JPEG_BASE+0x24))
#define rJPEG_WREND                               					*((volatile unsigned int *)(JPEG_BASE+0x28))
#define rJPEG_CTRL                                					*((volatile unsigned int *)(JPEG_BASE+0x2c))
#define rJPEG_START                               					*((volatile unsigned int *)(JPEG_BASE+0x30))
#define rJPEG_INTCTRL                             					*((volatile unsigned int *)(JPEG_BASE+0x34))
#define rJPEG_INTMASK                             					*((volatile unsigned int *)(JPEG_BASE+0x38))
#define rJPEG_INTCLR                              					*((volatile unsigned int *)(JPEG_BASE+0x3c))
#define rJPEG_LINE_NUM                            					*((volatile unsigned int *)(JPEG_BASE+0x40))
#define rJPEG_FIFO                                					*((volatile unsigned int *)(JPEG_BASE+0x44))
#define rJPEG_WRSTA1                              					*((volatile unsigned int *)(JPEG_BASE+0x48))
#define rJPEG_WREND1                              					*((volatile unsigned int *)(JPEG_BASE+0x4c))
#define rJPEG_COUNT                               					*((volatile unsigned int *)(JPEG_BASE+0x50))
#define rJPEG_WRSTA2                              					*((volatile unsigned int *)(JPEG_BASE+0x54))
#define rJPEG_WREND2                              					*((volatile unsigned int *)(JPEG_BASE+0x58))
#define rJPEG_TEST                                					*((volatile unsigned int *)(JPEG_BASE+0x88)) 
#define rJPEG_dec_rd_base_addr							*((volatile unsigned int *)(JPEG_BASE+0x5c)) 
#define rJPEG_enc_rd_base_addr							*((volatile unsigned int *)(JPEG_BASE+0x60)) 
#define rJPEG_enc_wr_base_addr							*((volatile unsigned int *)(JPEG_BASE+0x64)) 

#define rJPEG_QT					                             		(JPEG_BASE+0x100)
#define rJPEG_SYMB					                           		(JPEG_BASE+0x500) 
#define rJPEG_BASE					                           		(JPEG_BASE+0xe00) 
#define rJPEG_MIN					                            	(JPEG_BASE+0xf00) 

/* VIC */
#define rVICL_IRQ_STATUS								*((volatile unsigned int *)(VICL_BASE + 0x000))
#define rVICL_FIQ_STATUS								*((volatile unsigned int *)(VICL_BASE + 0x004))
#define rVICL_RAW_INTR									*((volatile unsigned int *)(VICL_BASE + 0x008))
#define rVICL_INT_SELECT								*((volatile unsigned int *)(VICL_BASE + 0x00C))
#define rVICL_INT_ENABLE								*((volatile unsigned int *)(VICL_BASE + 0x010))
#define rVICL_INT_ENCLEAR								*((volatile unsigned int *)(VICL_BASE + 0x014))
#define rVICL_SOFT_INT									*((volatile unsigned int *)(VICL_BASE + 0x018))
#define rVICL_SOFT_INTCLEAR								*((volatile unsigned int *)(VICL_BASE + 0x01C))
#define rVICL_PROTECTION								*((volatile unsigned int *)(VICL_BASE + 0x020))
#define rVICL_SWPRIORITY_MASK							*((volatile unsigned int *)(VICL_BASE + 0x024))
#define rVICL_PRIORITY_DAISY							*((volatile unsigned int *)(VICL_BASE + 0x028))

#define rVICL_VECT_ADDR0								*((volatile unsigned int *)(VICL_BASE + 0x100))
#define rVICL_VECT_PRIORITY0							*((volatile unsigned int *)(VICL_BASE + 0x200))
#define rVICL_ADDRESS									*((volatile unsigned int *)(VICL_BASE + 0xF00))


#define rVICH_IRQ_STATUS								*((volatile unsigned int *)(VICH_BASE + 0x000))
#define rVICH_FIQ_STATUS								*((volatile unsigned int *)(VICH_BASE + 0x004))
#define rVICH_RAW_INTR									*((volatile unsigned int *)(VICH_BASE + 0x008))
#define rVICH_INT_SELECT								*((volatile unsigned int *)(VICH_BASE + 0x00C))
#define rVICH_INT_ENABLE								*((volatile unsigned int *)(VICH_BASE + 0x010))
#define rVICH_INT_ENCLEAR								*((volatile unsigned int *)(VICH_BASE + 0x014))
#define rVICH_SOFT_INT									*((volatile unsigned int *)(VICH_BASE + 0x018))
#define rVICH_SOFT_INTCLEAR							*((volatile unsigned int *)(VICH_BASE + 0x01C))
#define rVICH_PROTECTION								*((volatile unsigned int *)(VICH_BASE + 0x020))
#define rVICH_SWPRIORITY_MASK							*((volatile unsigned int *)(VICH_BASE + 0x024))
#define rVICH_PRIORITY_DAISY							*((volatile unsigned int *)(VICH_BASE + 0x028))

#define rVICH_VECT_ADDR0								*((volatile unsigned int *)(VICH_BASE + 0x100))
#define rVICH_VECT_PRIORITY0							*((volatile unsigned int *)(VICH_BASE + 0x200))
#define rVICH_ADDRESS									*((volatile unsigned int *)(VICH_BASE + 0xF00))

/* GPIO */
#define rGPIO_PA_MOD									(*(volatile unsigned int *)(GPIO_BASE + 0x00))
#define rGPIO_PA_RDATA									(*(volatile unsigned int *)(GPIO_BASE + 0x04))
#define rGPIO_PA_INTEN									(*(volatile unsigned int *)(GPIO_BASE + 0x08))
#define rGPIO_PA_LEVEL									(*(volatile unsigned int *)(GPIO_BASE + 0x0C))
#define rGPIO_PA_PEND									(*(volatile unsigned int *)(GPIO_BASE + 0x10))

#define rGPIO_PB_MOD									(*(volatile unsigned int *)(GPIO_BASE + 0x20))
#define rGPIO_PB_RDATA									(*(volatile unsigned int *)(GPIO_BASE + 0x24))
#define rGPIO_PB_INTEN									(*(volatile unsigned int *)(GPIO_BASE + 0x28))
#define rGPIO_PB_LEVEL									(*(volatile unsigned int *)(GPIO_BASE + 0x2C))
#define rGPIO_PB_PEND									(*(volatile unsigned int *)(GPIO_BASE + 0x30))

#define rGPIO_PC_MOD									(*(volatile unsigned int *)(GPIO_BASE + 0x40))
#define rGPIO_PC_RDATA									(*(volatile unsigned int *)(GPIO_BASE + 0x44))
#define rGPIO_PC_INTEN									(*(volatile unsigned int *)(GPIO_BASE + 0x48))
#define rGPIO_PC_LEVEL									(*(volatile unsigned int *)(GPIO_BASE + 0x4C))
#define rGPIO_PC_PEND									(*(volatile unsigned int *)(GPIO_BASE + 0x50))

#define rGPIO_PD_MOD									(*(volatile unsigned int *)(GPIO_BASE + 0x60))
#define rGPIO_PD_RDATA									(*(volatile unsigned int *)(GPIO_BASE + 0x64))
#define rGPIO_PD_INTEN									(*(volatile unsigned int *)(GPIO_BASE + 0x68))
#define rGPIO_PD_LEVEL									(*(volatile unsigned int *)(GPIO_BASE + 0x6C))
#define rGPIO_PD_PEND									(*(volatile unsigned int *)(GPIO_BASE + 0x70))

#define rGPIO_DEBOUNCE_CNT_0							(*(volatile unsigned int *)(GPIO_BASE + 0x80))
#define rGPIO_DEBOUNCE_CNT_1							(*(volatile unsigned int *)(GPIO_BASE + 0x84))
#define rGPIO_DEBOUNCE_CNT_2							(*(volatile unsigned int *)(GPIO_BASE + 0x88))
#define rGPIO_DEBOUNCE_CNT_3							(*(volatile unsigned int *)(GPIO_BASE + 0x8c))
#define rGPIO_DEBOUNCE_CNT_4							(*(volatile unsigned int *)(GPIO_BASE + 0x90))
#define rGPIO_DEBOUNCE_CNT_5							(*(volatile unsigned int *)(GPIO_BASE + 0x94))
#define rGPIO_DEBOUNCE_CNT_6							(*(volatile unsigned int *)(GPIO_BASE + 0x98))
#define rGPIO_DEBOUNCE_CNT_7							(*(volatile unsigned int *)(GPIO_BASE + 0x9c))
#define rGPIO_DEBOUNCE_ENABLE							(*(volatile unsigned int *)(GPIO_BASE + 0xA0))

/* WDT */
#define rWDT_CR										(*(volatile unsigned int *)(WDT_BASE + 0x00))
#define rWDT_PSR										(*(volatile unsigned int *)(WDT_BASE + 0x04))
#define rWDT_LDR										(*(volatile unsigned int *)(WDT_BASE + 0x08))
#define rWDT_VLR										(*(volatile unsigned int *)(WDT_BASE + 0x0C))
#define rWDT_ISR										(*(volatile unsigned int *)(WDT_BASE + 0x10))
#define rWDT_RCR										(*(volatile unsigned int *)(WDT_BASE + 0x14))
#define rWDT_TMR										(*(volatile unsigned int *)(WDT_BASE + 0x18))
#define rWDT_TCR										(*(volatile unsigned int *)(WDT_BASE + 0x1C))

#endif /* ARK_SYS_H */
