
obj-y += ark1668.o

ifeq ($(CONFIG_SPL_BUILD),)
obj-y += ark1668_display_cfg.o
obj-y += ark1668_lcd.o
obj-y += ark1668_debug_cmds.o
obj-y += ark1668_arkdata_ini.o
obj-y += ark1668_lcd_console.o
obj-y += ark1668_boot_cmds.o

endif