ctrl_interface=/var/run/wpa_supplicant
update_config=1
device_name=My_P2P_Device
device_type=1-0050F204-1
config_methods=display push_button keypad virtual_push_button physical_display
p2p_no_group_iface=1
p2p_go_max_inactivity=72000
wowlan_triggers=any
