#----------------------------------------------------------------------------------------
# Feasycom Bluetooth Stack Configuration @20200417
#----------------------------------------------------------------------------------------

# support module list: BT805B/BT805C/BT805D/BT825B/BW101/BW121/BW161
MODULE_TYPE=BW121

# sepcial configuration for module
MODULE_CFG=

# dir for blueware cache files,such as log,phonebook database and etc.
CACHE_PATH=/data/feasycom/

# dir for blueware log files, don't generate log.txt if not set
LOGCAT_PATH=/data/feasycom/
# 0:disable
# BIT[0]:ALOGD with TAG "blueware"
# BIT[1]:fprintf(stdout,"...")
# BIT[2]:BTSNOOP
LOGCAT_TYPE=3

# for chipset without build-in mac address
BT_ADDR_PATH=

# gpio for BT_ENABLE hardware pin control
# available option:
# gpioNUM (path:/sys/class/gpio/gpioNUM)
# rfkill(path:/sys/class/rfkill)
# gpioPATH,NUM for ioctl operation,e.g: /dev/gpio_imx6:123
BTEN_INTERFACE=gpio79

# uart interface & baudrate between host platform and module
# available baudrate: 921600/1M/1.5M/2M/2.5M/3M/3.5M/4M
UART_INTERFACE=/dev/ttyHS0
UART_BAUDRATE=1500000
UART_FLOWCTL=0

# voice type between host platform and module,PCM (recommended) or UART
VOICE_TYPE=UART
# pcm card,device id for voice call of btchipset
# e.g: 1,0 means /dev/pcmC1D0c for capture,/dev/pcmC1D0p for playback
# Do not set if platform control pcm directly (bypass bluetooth stack)
BT_PCM_INTERFACE=

# pcm card,device id for audio playback/capture of host platform
# set proper value if target platform is linux+asound,otherwise value "default" will be used
HOST_PCM_INTERFACE=
HOST_AUD_CHANNEL=

# millionseconds between sco establishment and audio routing (mic/speaker setup)
VOICE_ROUTE_DELAY=800
VOICE_ECHO_DELAY=250
# save sco voice to $(CachePath)/playback.pcm and $(CachePath)/capture.pcm [default:0]
VOICE_DUMP=0

# override default device name for BR/EDR classic mode [default:FSC-CARKIT]
LOCAL_NAME=

# override default device name for LE mode [default:FSC-CARKIT-LE]
LOCAL_LENAME=

# 0:legacy pairing, use LocalPin as pin code
# 1:secure simple pairing, auto pair
# 2:secure simple pairing, display yes/no [default]
# 3:secure simple pairing, passkey compare, user need to accept/reject pair request 
PAIR_MODE=2

# pairing pin code (only work for legacy pairing mode) [default:0000]
LOCAL_PIN=

# 0:auto remove earliest paired record when paired records full [default]
# 1~8: stop enter pairing mode when paired records full
PAIR_RECORDS=

# use stdin terminal as AT command console, e.g. type "name" for command:AT+NAME\r\n
CONSOLE_ENABLE=0

# 0: auto enable/disable according to previous state (default DISABLE) 
# 1: auto enable/disable according to previous state (default ENABLE) 
# 2: always stay in disable 
BT_ENABLE=1

# hfp profile enable [default:1]
HFP_ENABLE=1

# auto reconnect hfp profile after power on [default:1]
HFP_PWR_REC=

# enable noise reduction and echo cancellation for voice call [default:0]
HFP_NREC=3

# resampler hfp audio bewteen 8Khz & 44.1Khz/48Khz [default:0]
HFP_RESAMPLER=0

# enable hfp sco wideband speech support
HFP_WBS=0

# enable hfp three way calling [default:0]
HFP_3WAY_CALLING=0

# play a specify stereo wav file when call incoming for phones without in-band-ring support
# e.g: /data/misc/feasycom/ringtone.wav
HFP_RING_PATH=/system/mtc/RingTone.wav

# a2dp profile enable [default:1]
A2DP_ENABLE=1

# a2dp decoder selection [default:1]
# BIT[0]:SBC (mandatory)
# BIT[1]:AAC (optional)
A2DP_DECODER=1

# avrcp profile enable [default:1]
AVRCP_ENABLE=1

# music player id3 information (title,artist,album) enable [default:1]
AVRCP_ID3=1

# music player play progress report, 1~9 seconds per report [default:1]
AVRCP_PLAYPROGRESS=0

# music player file system folder browsing enable [default:0]
AVRCP_BROWSING=0

# music player cover art image automatic download enable [default:0]
AVRCP_COVERART=0

# dir for cover art image files, use $(CACHE_PATH)/cover by default if not set
# pixel 200*200 jpg file will be placed in dir $(COVERART_PATH)
# e.g /data/misc/feasycom/cover/1000435.jpg
COVERART_PATH=

# phonebook access profile enable [default:1]
PB_ENABLE=1

# phonebook build-in database enable
# build-in database is recommended for application without database management [default:0]
PB_DATABASE=0

# dir for phonebook contacts photo image files, use $(CACHE_PATH)/photo by default if not set
# jpg file will be placed in dir $(PHOTO_PATH)
# e.g /data/misc/feasycom/photo/10086.jpg
PHOTO_PATH=

# dump raw vcard to $(CachePath)/vcard.vcf for debug purpose when enabled [default:0]
PB_DUMP=0

# Message Access Profile enable [default:0]
MAPC_ENABLE=0

# Personal Area Networking Profile enable (user role) [default:0]
PANU_ENABLE=0

# serial port profile & interface(socket) [default:0]
SPP_ENABLE=0

# iAP2 profile & interface(socket) [default:0]
IAP2_ENABLE=1

# Android Auto Projection & interface(socket) [default:0]
AAP_ENABLE=1

HICAR_ENABLE=1
# GATT profile profile enable.1:server(peripheral);2:client(central) [default:0]
GATT_ENABLE=1
#----------------------------------------------------------------------------------------