 #简体中文

_@M000_	""

#setup
_@M001_	"行车电脑"
_@M002_	"轮胎信息"
_@M003_	"亮度调节"
_@M004_	"主题风格"
_@M005_	"系统设置"
_@M006_	"亮度调节"
_@M007_	"小计里程"
_@M008_	"平均车速"
_@M009_	"平均能耗"
_@M010_	"行驶时间"
_@M011_	"胎压显示"
_@M012_	"按OK键常显"
_@M013_	"胎压异常"
_@M014_	"驻车制动未解除"
_@M015_	"系统故障"
_@M016_	"动力电池切断"
_@M017_	"动力蓄电池故障"
_@M018_	"ABS故障"
_@M019_	"EBD故障"
_@M020_	"EPS系统故障"
_@M021_	"电机过热"
_@M022_	"降功耗模式"
_@M023_	"绝缘电阻低"
_@M024_	"制动液不足"
_@M025_	"ESCL故障"
_@M026_	"没有发现智能钥匙"
_@M027_	"请踩刹车启动"
_@M028_	"钥匙电量低"
_@M029_	"请将钥匙靠近启动按钮启动"
_@M030_	"车内无有效钥匙"
_@M031_	"钥匙遗忘在车内"
_@M032_	"请踩制动踏板"
_@M033_	"请释放EPB开关"
_@M034_	"车门未关"
_@M035_	"总里程(Km)："
_@M036_	"小计里程(Km)："
_@M037_	"默认设置"
_@M038_	"恢复默认设置？"
_@M039_	"确认"
_@M040_	"取消"
_@M041_	"剩余时间："
_@M042_	"充电时间："
_@M043_	"电控温度:"
_@M044_	"℃"
_@M045_	"电机温度:"
_@M046_	"即将进行升级："
_@M047_	"升级中，请勿断电"
_@M048_	"来电号码"
_@M049_	"去电号码"
_@M050_	"充电时间"
_@M051_	"-40"
_@M052_	"电控（℃）215"
_@M053_	"215 电机（℃）"
_@M054_	"可行驶里程"
_@M055_	"清零设置"
_@M056_	"恢复出厂"
_@M057_	"版本信息"
_@M058_	"小计里程清零"
_@M059_	"平均能耗清零"
_@M060_	"平均车速清零"
_@M061_	"确认清零？"
_@M062_	"平均车速(Km/h)："
_@M063_	"平均能耗(kwh/100km)："
_@M064_	"可行驶里程(Km)："
_@M107_ ""